### ISSUE TITLE
Hosted Postman Collections

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#100]
https://www.postman.com/postman/workspace/httpbin/request/15582611-23a19640-0289-494e-ba46-a38f997b7012

^ investigate, can we provide a UI on the collections in this repo?

**Comment by brownoxford** [comment]
Publishing the postman tests for people to use would be a great way to lower barrier to entry for new users.

**Comment by nissimsan** [comment]
Try this on api.did.actor first

**Comment by nissimsan** [comment]
How about this: 
https://www.postman.com/trace-interop/workspace/traceability-interop/overview

Let's discuss before progressing further. Is this at all what we're aiming for? A few notes and todos: 

- The collections were manually imported (Import Link -> link to raw collection). Ideally this would be automatically generated to make sure it's properly up-to-date. Newman doesn't seem to support importing, though, not sure how to potentially do that. 

- It's a public workspace for a `trace-interop` team. You should be able to join the team with this link:
https://app.getpostman.com/join-team?invite_code=74125d75f27465c573844962880bf923&target_code=27e1d452646a56288bdc291c59622fcf
(Postman only supports one team per user, so you probably want to make a new user. Be careful, postman is pretty aggressive sharing your personal workspaces with the team you join.)

**Comment by OR13** [comment]
Initial react is that this seems promising.

The navigation is excellent, I wonder if we could script export to files from this.

the environment config part is worrying though... it feels like stuff that should not be on the web... not sure how to handle that part.

**Comment by nissimsan** [comment]
<img width="856" alt="image" src="https://user-images.githubusercontent.com/34443212/164253958-0cec3a2a-7364-413d-8b95-035d50a526ae.png">
As long as only `Current Value` is used in the Environment it should be safe. I just added an empty environment this way.

**Comment by OR13** [comment]
Next steps:

1. add a link to the top level readme
2. add scripts / documentation for keeping the hosted version in sync.

**Comment by nissimsan** [comment]
... @brownoxford , maybe?

**Comment by nissimsan** [comment]
Start by adding raw links to README

Investigate if there a thing such as Postman-hub? That would be appropriate

**Comment by BenjaminMoe** [comment]
No action has been taken on this issue.

**Comment by kgobin2000** [comment]
Could I get a link to join the postman `trace-interop` team? The previous invite expired.

**Comment by nissimsan** [comment]
@kgobin2000, I don't think I understand your question? You're here already. :) 
You can find all the postman collections here: https://github.com/w3c-ccg/traceability-interop/tree/main/docs/tutorials

Pls elaborate if I misunderstood what you're asking.

**Comment by kgobin2000** [comment]
I wanted to verify/create integrations to sync the collection with Github if they don't already exist. The previous invite link ([https://app.getpostman.com/join-team?invite_code=74125d75f27465c573844962880bf923&target_code=27e1d452646a56288bdc291c59622fcf](url)) expired

**Comment by nissimsan** [comment]
Oh, I see. Yea, that was convenient to have the collections listed in Postman. We're kinda going in a slightly different direction, though, just listing collections somewhere here on an .md file, mainly because we don't need to maintain a postman account alongside the "actual" stuff here. 

It's (almost) as easy to use, though: 
- Go to the tutorials I linked above. 
- Find the one you want to run (like the [Verify Credential](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/tutorials/credentials-verify/credentials-verify.postman_collection.json) one)
- Copy the "Raw" link to that file (https://github.com/w3c-ccg/traceability-interop/raw/main/docs/tutorials/credentials-verify/credentials-verify.postman_collection.json). 
- In Postman, import -> link -> past the raw link. 
- Boom - there's the collection in Postman, ready to run.

**Comment by nissimsan** [comment]
I'd love to see these listed on https://w3c-ccg.github.io/traceability-interop/ too before closing.

**Comment by nissimsan** [comment]
@OR13, you okay to close?

**Comment by OR13** [comment]
yes
