### ISSUE TITLE
Can we close branches which have been merged?

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#105]
What is the policy for feature and fix branches which have been merged, can those be deleted to clear out clutter? To be clear, I am volunteering to do this cleanup :)

**Comment by OR13** [comment]
as soon as a branch is merged it should be closed.

**Comment by brownoxford** [comment]
I've closed all outstanding branches that have been merged into `main` already. The following un-merged branches remain, and all of them seem like they can be deleted, but I wanted to discuss with the group first to confirm:

`remotes/origin/correlation-data-model` - Open branch by @nissimsan  for Closed PR #70
`remotes/origin/feat/add-revocation-list-endpoint` - Open branch by @OR13  for Closed PR #65
`remotes/origin/msporny-test-pr-preview` - Open branch by @msporny  for Closed PR #86

**Comment by nissimsan** [comment]
The PR https://github.com/w3c-ccg/traceability-interop/pull/70 one is now closed.

**Comment by brownoxford** [comment]
Spoke with @OR13 offline and got the go-ahead to remove the branch for #65

**Comment by msporny** [comment]
> @msporny, can we delete the branch you had created for #86?

Yep, delete away.

**Comment by brownoxford** [comment]
All orphan and merged branches have been cleaned up, closing this ticket.
