### ISSUE TITLE
PROPOSAL: Define Client Credentials for APIs

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#11]
HTTP API integrations between trusted parties are a solved problem and do not require a new spec to provide support for the authorization we need.

- https://auth0.com/machine-to-machine
- https://developer.okta.com/docs/guides/implement-client-creds/overview/

These "Client Credentials" solutions are appropriate starting point for cross trust domain VC HTTP API operations.

This ticket seeks to gain consensus on their use with the vc http api.

For the sake of simplicity, lets assume 2 vendors wish to exchange presentations over https.

Vendor A -> Client Credentials App for Vendor B -> Vendor B uses app to access Vendor A's API.
Vendor B -> Client Credential App for Vendor A -> Vendor A uses app to access Vendor B's API.

OAuth client credentials setup is out of scope, but let us assume that each integration is identified with a CLIENT_ID and authenticated via a CLIENT_SECRET.

Before authenticated exchanges can be made, an application `access_token`'s for each app must be obtained using the client credentials.

Vendor A's software integration uses the client credentials from Vendor B's client credentials app and vendor b's IDP to obtain an access token, see these docs for the standard way this is accomplished: [auth0](https://auth0.com/blog/using-m2m-authorization/)

```
curl --location --request POST 'https://vendor-b.auth0.com/oauth/token' \
--header 'Content-Type: application/json' \
--data-raw '{
"client_id": "A's integration app for B's API",
"client_secret": "[You application client secret]",
"audience": "https://vendor-b.example.com",
"grant_type": "client_credentials"
}
```

once Vendor A' software has an `access_token` for Vendor B's API, the presentation exchange can begin, the flow is as follows:

###  Getting a Challenge for a flow

```
curl POST -H "Authorization: <ACCESS_TOKEN>" \
http://www.vendor-b.example.com/organizations/123/presentations/available  \
-d @./get-challengge-token-with-query-by-frame.json
```

```json
{
  "query": [
    {
      "type": "RequestQueryByFrame",
      "credentialQuery": [
        {
          "type": [
            "VerifiableCredential",
            "CommercialInvoiceCertificate"
          ],
          "reason": "Wallet XYZ is ready to selectively disclose new credentials."
        }
      ]
    }
  ]
}
```

Response is expected to look like this:

```json
{
  "query": [
    {
      "type": "QueryByFrame",
      "credentialQuery": {
        "frame": {
          "@context": [
            "https://www.w3.org/2018/credentials/v1",
            "https://w3id.org/traceability/v1",
            "https://w3id.org/bbs/v1"
          ],
          "type": [
            "VerifiableCredential",
            "CommercialInvoiceCertificate"
          ],
          "credentialSubject": {
            "@explicit": true,
            "type": [
              "CommercialInvoice"
            ],
            "purchaseDate": {},
            "destinationCountry": {}
          }
        }
      }
    }
  ],
  "domain": "vendor-b.example.com",
  "challenge": "3182bdea-63d9-11ea-b6de-3b7c1404d57f"
}
```

### Submitting a Presentation

```
curl POST -H "Authorization: <ACCESS_TOKEN>" \
http://www.vendor-b.example.com/organizations/123/presentations/submissions  \
-d @./submit-presentation.json
```

```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "holder": "did:example:123",
  "type": "VerifiablePresentation",
  "verifiableCredential": [
    {
      "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://www.w3.org/2018/credentials/examples/v1"
      ]
    },
    {
      "id": "http://example.gov/credentials/3732"
    },
    {
      "type": [
        "VerifiableCredential",
        "UniversityDegreeCredential"
      ]
    },
    {
      "issuer": "did:example:123"
    },
    {
      "issuanceDate": "2020-03-16T22:37:26.544Z"
    },
    {
      "credentialSubject": {
        "id": "did:example:123",
        "degree": {
          "type": "BachelorDegree",
          "name": "Bachelor of Science and Arts"
        }
      }
    },
    {
      "proof": {
        "type": "Ed25519Signature2018",
        "created": "2020-04-02T18:28:08Z",
        "verificationMethod": "did:example:123#z6MksHh7qHWvybLg5QTPPdG2DgEjjduBDArV9EF9mRiRzMBN",
        "proofPurpose": "assertionMethod",
        "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..YtqjEYnFENT7fNW-COD0HAACxeuQxPKAmp4nIl8jYAu__6IH2FpSxv81w-l5PvE1og50tS9tH8WyXMlXyo45CA"
      }
    }
  ],
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2020-04-02T18:28:08Z",
    "verificationMethod": "did:example:123#z6MksHh7qHWvybLg5QTPPdG2DgEjjduBDArV9EF9mRiRzMBN",
    "proofPurpose": "assertionMethod",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..YtqjEYnFENT7fNW-COD0HAACxeuQxPKAmp4nIl8jYAu__6IH2FpSxv81w-l5PvE1og50tS9tH8WyXMlXyo45CA"
  }
}
```

**Comment by mprorock** [comment]
I like this flow - OAuth works well in this case and the way you are lining out the `/organizations/...` path sets things up well for the multi-tenant situations we are seeing in the real world

**Comment by OR13** [comment]
thanks, I think we already have evidence that some vc http api endpoints will be isolated and authenticated on a per tenant basis, whether thats via a subdomain or a path.

**Comment by Therecanbeonlyone1969** [comment]
100% agree with this approach!

We could advocate that people list their endpoints for the VC HTTP API and the authorization in the DID docs of the organizations did doc and put that into the well-known path for discoverability. then the only thing that remains is the identity set up of A and B in each other's apps. But that can follow the already known and used methods that enterprises love and cherish. cc @OR13 @mprorock

**Comment by mprorock** [comment]
nb: closely related to #3

**Comment by mprorock** [comment]
great note from @TallTed on weekly call that auth should likely apply to all APIs in this spec

**Comment by OR13** [comment]
partially addressed in https://github.com/w3c-ccg/traceability-interop/pulls

**Comment by OR13** [comment]
On the call today, we discussed 2 options regarding accesss_token and scope.

Consensus was too not put scopes into the flow, until the API is more mature/

**Comment by TallTed** [comment]
I talked about DBMS analogies on the call; the basic web architecture also fits.

DBMS "native" API carries ODBC/JDBC/dotNET/OLE DB/etc. carries app data and/or logic of varying depths which may require varying authentication *and* authorization, typically to the CATALOG or SCHEMA or TABLE or ROW or even CELL.

TCP/IP carries TLS carries HTTP (making it HTTPS) carries app data and/or logic of varying depths which may require varying authentication *and* authorization, to the directory/container or file or segment of file, etc.

It's important to build to allow the very very low-level, though early efforts may only require the high level at the beginning -- with the eternal caution that some early deployments may linger for decades past their expected expiration date (_note bene_ the FORTRAN and COBOL that still powers the financial industry, not to mention [if I remember right] still-lingering pieces of the air-traffic-control system!) ... so always be careful what you put defaults i

**Comment by OR13** [comment]
related:

- https://swagger.io/specification/
- https://swagger.io/docs/specification/authentication/

**Comment by OR13** [comment]
implemented in spec, pending close once new issue addressing the links above is raised.

**Comment by OR13** [comment]
Opened, here: https://github.com/w3c-ccg/vc-http-api/issues/218
