### ISSUE TITLE
Newman test reports must be sanitized

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#112]
Creating a ticket as a placeholder to ensure that we sanitize newman reports before publishing them to github pages.

**Comment by brownoxford** [comment]
Current known issues:
* Bearer token is present in request authorization headers
* Bearer token is exposed in response body from token provider
* Client ID and Secret are exposed in request body to token provider

**Comment by mkhraisha** [comment]
Should probably add a reminder here to re-issue new tokens, and Client IDs and Secrets after this is resolved

**Comment by brownoxford** [comment]
Not a bad idea, but to clarify the JS based testing that lives in the `tests-postman` package is currently doing the correct sanitization, no tokens or secrets are known to have been exposed at this point.

**Comment by nissimsan** [comment]
Closed, we just merged PR doing this. PR-148
