### ISSUE TITLE
Openapi DidResolutionResponse should include alsoKnownAs

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#118]
The  [Openapi definition](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/DidResolutionResponse.yml#L3-L4) for the `DidResolutionResponse` element should be updated to reflect the `MUST be present` requirement for `alsoKnownAs` as [outlined in the discovery profile](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/discovery.md?plain=1#L43) in `docs/discovery.md`

**Comment by brownoxford** [comment]
Tests should also be updated to ensure that alsoKnownAs has at least two elements - the first is required to match the API_BASE_URL used in the test, and the second will be used as a did for issuing VCs in test suites.

**Comment by nissimsan** [comment]
As defined in https://github.com/w3c-ccg/traceability-interop/blob/main/docs/discovery.md

**Comment by OR13** [comment]
File that needs to be updated: https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/DidResolutionResponse.yml

**Comment by OR13** [comment]
This is specific to our use of did web.

**Comment by brownoxford** [comment]
This may need some slight modification to reflect our use of the service array

**Comment by brownoxford** [comment]
> This may need some slight modification to reflect our use of the service array

We no longer require `alsoKnownAs[0]` to match `API_BASE_URL`, but we do still use alsoKnownAs[1] as the `credential.issuer` value when subsequently issuing credentials. Postman tests have already been updated to reflect these items, so the only outstanding work here is to update the openapi spec.
