### ISSUE TITLE
PROPOSAL: Add Encryption in Transport Guidelines

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-interop#12]
Need to add guidelines for which encryption methods are suggested for use of communications over the network, e.g. TLS 1.3, along with suggested cipher suites

**Comment by OR13** [comment]
@mprorock can you add a description to this issue, and make it actionable.

**Comment by mprorock** [comment]
@mprorock to add content

**Comment by OR13** [comment]
@mprorock agreed to add content on the call today.

**Comment by TallTed** [comment]
Better titling on things like this can be helpful -- e.g., 

* PROPOSAL: Add "Encryption in Transport" Guidelines
* PROPOSAL: Add Guidelines for "Encryption in Transport"

**Comment by mprorock** [comment]
in progress, have not yet opened pr

**Comment by mkhraisha** [comment]
@mprorock have you been able to work on this?

**Comment by nissimsan** [comment]
@mprorock , will you action this, pls?
