### ISSUE TITLE
Need to define scopes or roles

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-interop#124]
#### The the interop profile needs to define scopes or roles.

![Screen Shot 2022-03-15 at 9 37 32 AM](https://user-images.githubusercontent.com/8295856/158402184-722e9f26-be40-4c1c-adc9-61ebff9ffcc1.png)

![Screen Shot 2022-03-11 at 10 34 41 AM](https://user-images.githubusercontent.com/8295856/157909210-2b5c9fab-2e96-4000-9971-4b8c2e866853.png)

In this example, you can see that there are basically 2 security contexts.

1. A client credentials app that is authorized to request a proof on a presentation.
1. A client credentials app that is authorized to present to an api.

Our current security model does not define a safe way to do this.

The current api profile only provides authentication of the client, with the implied assumption that the client can do EVERYTHING the api defines.

This is highly problematic.

Additionally, an entity would prefer to create applications only scoped to presenting data, and NEVER allowed to do anything else.

This can be solved for in 2 ways, but only one of them will be an interoperable standard.

### Option 1

Use OAuth2 scopes.

Example: https://github.com/OR13/GNARLY/blob/main/docs/openapi.yaml#L55

### Option 2

Bind `sub` for client tokens to an internal `role` like "credential_presenter".

Example: https://en.wikipedia.org/wiki/Role-based_access_control

Option 2 is a bad idea, since everyone will define their own "roles" ... which will make configuration management extremely painful.

**Comment by OR13** [comment]
As a side note, if we addressed this first: https://github.com/w3c-ccg/traceability-interop/issues/95

6 network requests would become only 2.

**Comment by nissimsan** [comment]
> As a side note, if we addressed this first: https://github.com/w3c-ccg/traceability-interop/issues/95
> 6 network requests would become only 2.

Yes. To complete the picture: Each org would have to obtain two access tokens. So those 2 network requests would become 4.

**Comment by nissimsan** [comment]
@mprorock, to your Option 1 vs 2, I'm pretty sure I completely agree with your argument. Allow me to attempt to say the same with my own words: 
Each vendor (mesur, transmute, etc) will obviously allow customers to control various levels of access, distinguishing e.g. between full tenant "admin” vs. limited "presenter". These roles will be platform-dependant, so enforcing policies will be kept internal within the platforms; endpoints will throw 401s when a token does not allow permission to the called operation. A token may allow calling `/submissions`, but not `/deleteTenant`.

**Comment by brownoxford** [comment]
Are we thinking something along these lines? The names I used are kind of arbitrary at this point, I think the more important bit to hammer out first is which scopes are required to use each endpoint.

`did:resolve`
- required for `GET /identifiers/{did}`

`vc:create`
- required for `POST /api/credentials/issue`

`vc:verify`
- required for `POST /api/credentials/verify`, maybe combine with `vc:read`?

`vc:read`
- required for `GET /credentials/{credential-id}`

`vp:create`
- required for `POST /api/presentations/prove`

`vp:verify`
- required for `POST /api/presentations/verify`

`vp:exchange`
- required for `POST /api/presentations/available`
- required for `POST /api/presentations/submissions`

**Comment by brownoxford** [comment]
> Yes. To complete the picture: Each org would have to obtain two access tokens. So those 2 network requests would become 4.

@nissimsan Trying to wrap my head around this, can you clarify for me? For the purposes of interoperability testing, we could easily define a client app in our auth provider which could request all scopes needed in a single token. I'm trying to understand why we would need two separate tokens (negative testing maybe?).

**Comment by nissimsan** [comment]
@brownoxford, no big deal, I was just pointing out that an authentication call before presenting is still needed. Each application would need two access tokens: one for "its own" platform (with `vc:create`, `vp:create`, etc) and one for the "presentee" platform (with `vp:exchange`).
So yes, the 6 presentation calls become 2 - but the 2 access token calls become 4.

**Comment by nissimsan** [comment]
@brownoxford et al., looking at some of [Auth0's examples](https://auth0.com/docs/get-started/apis/scopes/api-scopes) and particularly [github](https://github.com/settings/tokens/new), they seem aligned on a naming scopes as first verb, then `:`, then the resource type. For example `transfer:funds` (auth0) and `read:user` (github). 

So for lack of a better convention, I suggest we align to that and switch around the naming: 
`resolve:did`
`create:vc`
`verify:vc`
`read:vc`
`create:vp`
`verify:vp`
`exchange:vp`
