### ISSUE TITLE
PROPOSAL: Add encryption at rest guidelines

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-interop#13]
Need to add a list of required or suggested encryption methods for storing information at rest in systems conforming to the spec, e.g. AESxxx

**Comment by OR13** [comment]
@mprorock Please update this description and make it actionable.

**Comment by OR13** [comment]
Feels like this should be informative recommendation for storage.

**Comment by OR13** [comment]
@mprorock to add a comment.

**Comment by mprorock** [comment]
in progress, have not yet opened pr

**Comment by mkhraisha** [comment]
@mprorock have you been able to work on this?

**Comment by mkhraisha** [comment]
This should be a list of suggested methods rather than a list of required methods

**Comment by nissimsan** [comment]
@mprorock , will you action this, pls?
