### ISSUE TITLE
CI Tests against deprecated packages

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-interop#133]
Our Current CI runs  `npm run test:all` which hits the deprecated tests-postman package instead of the postman tests
https://github.com/w3c-ccg/traceability-interop/blob/6dda5b06c49fe346953648a9b6a906dd5e60f78f/.github/workflows/ci.yml#L35

**Comment by brownoxford** [comment]
Yes, please do not run new tests via CI until we address sanitization issues in output reports.

**Comment by mkhraisha** [comment]
yup!
The CI auto runs right now, on any push/commit tracking old tests, should probably just remove that portion as it doesn't really do anything
