### ISSUE TITLE
Revocation Tutorial assumes response from credentials/issue is wrong format

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-interop#156]
Revocation tutorial assumes that credentials/issue responds with:
``` 
{
     credential: VC
}
```
VC API specifies it without the wrapper as

```
VC
```
Really hard to link to the VC-API open-API as the reporter there is currently broken.

**Comment by OR13** [comment]
hmm actually I think you are confusing the request a response types.

**Comment by OR13** [comment]
This behavior is correct https://api.did.actor/docs#post-/api/credentials/issue

**Comment by OR13** [comment]
The tutorial and our open api definitions here should be the same as the link and working example provided above^

(ignore the mnemonic stuff)

**Comment by mkhraisha** [comment]
Yup, so the tutorial is incorrect as it assumes the response is wrapped and tries to access a `credential` object :

```
"// Verifiable credential must be made available to later requests",
"pm.test(\"`verifiable_credential` persisted to collectionVariables\", function() {",
"    const verifiable_credential = JSON.stringify(pm.response.json());",
"    pm.collectionVariables.set(\"verifiable_credential\", verifiable_credential);",
"})",
```

![image](https://user-images.githubusercontent.com/19310771/161822760-0328859a-819e-4691-9651-25ce3f1186ff.png)
