### ISSUE TITLE
Postman interoperability tests and report automation

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#16]
@mprorock Our team wants to add client credentials for a CCG test report application to this repo, and generate a conformance report using postman.

Can we set this up in CI with no authorization first, and then figure out how to pull client id and client secret from github secrets in CI second?

- [ ] Wire CI tests for postman without authorization
- [ ] Add CLIENT_ID and CLIENT_SECRET to GitHub Secrets
- [ ] Update Postman tests to use authorization

**Comment by OR13** [comment]
@mprorock please leave a comment for the work to be done here.

**Comment by nissimsan** [comment]
This is quite focused on the authentication aspect of the spec. But as we discussed on the call today, these test scripts should also cover the data exchange aspects of the spec (the directional, cross-security domain elements), and those latter parts should also be included in the issue's description.

**Comment by mprorock** [comment]
We have added initial tests here a little while ago: [Trace Vocab](https://github.com/w3c-ccg/traceability-vocab/tree/main/packages/traceability-schemas/src/data/examples/tests)

As mentioned on the call we will be extending these out quite a bit over the next 30-90 days and migrating them to a more dynamic config that also covers broader items for interop in this repo

**Comment by mprorock** [comment]
will extend once we add spec on Auth

**Comment by mkhraisha** [comment]
@mprorock any updates on this?

**Comment by OR13** [comment]
See also https://github.com/w3c-ccg/vc-http-api/issues/234

**Comment by nissimsan** [comment]
Issue to be kept open until multiple vendors can show interoperability.

**Comment by mprorock** [comment]
have a polished version of this that I will PR this week - test suite may be homed outside the repo and pointed to from this project

**Comment by OR13** [comment]
Partially implemented in https://github.com/w3c-ccg/traceability-interop/pull/35

**Comment by mprorock** [comment]
#35 covers reporting in multiple formats for all current tests and rolling forward
