### ISSUE TITLE
PROPOSAL: Define support for DIDComm / WACI-PEx

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#17]
WACI-PEx describes an alternate flow for exchanging verifiable presentations:

https://github.com/decentralized-identity/waci-presentation-exchange

Unlike the vc-http-api, it is built on top of message level encryption for DIDs, according to a spec called https://github.com/decentralized-identity/didcomm-messaging

The advantage of WACI-PEx is that messages can flow other transports other than HTTP.

The spec also makes use of https://github.com/decentralized-identity/presentation-exchange

Which defines extensions for verifiable presentations that a verifier can use to request specific kinds of presentations from holders.

I would like to define support for this once it stabilizes so we can establish interoperability with other DIF companies and [TOIPs Good Health Pass](https://wiki.trustoverip.org/display/HOME/GHP+Blueprint+Public+Review+Process).

I think for sanity sake, we would need new endpoints for this, luckily they would be generate "DIDComm" service endpoints.

**Comment by Therecanbeonlyone1969** [comment]
we should put this into a implementation guide @OR13

**Comment by OR13** [comment]
There is progress being made, but v0.1 release has still not shipped.

**Comment by mprorock** [comment]
> There is progress being made, but v0.1 release has still not shipped.

discussed on call and will revist one v0.1 is in place

**Comment by OR13** [comment]
Status update: https://github.com/w3c-ccg/universal-wallet-interop-spec/issues/99

**Comment by mkhraisha** [comment]
Orie can you maybe walk us through this proposal

**Comment by nissimsan** [comment]
@OR13, we need to have you on the call for this.

**Comment by OR13** [comment]
I'm not in favor of adding DIDComm at this time.

I'm not in favor of adding WACI / Presentation Exchange at this time.

I am happy to leave this issue open or close it.

**Comment by OR13** [comment]
See also https://github.com/w3c-ccg/vc-api/issues/245

**Comment by nissimsan** [comment]
There are valid requirements for having vc pushed to your wallet. But this may belong better on vc-api.

**Comment by OR13** [comment]
and https://github.com/w3c-ccg/vc-api/issues/186

**Comment by TallTed** [comment]
I see issues similar to FTP(control,data) distinct connections, where special switches must be flipped in order to have the client initiate both connections, rather than having client initiate control and server initiate data.  This will need strong consideration in the VC API world, along push+pull vs pure_push vs pure_pull vs pull+push

**Comment by nissimsan** [comment]
Keeping this ticket around for keeping us updated

**Comment by OR13** [comment]
We discussed implementation timeline for WACI / PEx / DIDComm.

There is no timeline for their implementation here.

These related PRs might impact our decisions in the future:

- https://github.com/w3c-ccg/vc-api/pull/254
- https://github.com/w3c-ccg/vp-request-spec/pull/13

**Comment by OR13** [comment]
as discsused, we are all awaiting didcomm v2 imps

**Comment by OR13** [comment]
didcomm v2 implementations still not available.

**Comment by OR13** [comment]
https://github.com/hyperledger/aries-agent-test-harness/pull/444

Seems to be available now.

**Comment by OR13** [comment]
nearly there... https://github.com/hyperledger/aries-agent-test-harness/pull/449/files#diff-d758e1dd1d5111619dbff3cd50c095452bf9a0610c395909656138641d109e85R1349

**Comment by OR13** [comment]
https://github.com/decentralized-identity/waci-didcomm/issues/14

**Comment by OR13** [comment]
We won't close this until the issue above is addressed.

**Comment by OR13** [comment]
We still have not addressed the issue.

**Comment by nissimsan** [comment]
If no one is planning to implement didcomm, we should stop spending time discussion this issue.

**Comment by mkhraisha** [comment]
Closed
