### ISSUE TITLE
Credentials verification response needs additional work

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#176]
Right now the [documented response](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/VerificationResult.yml) from a credentials verification check specifies that there can be three string arrays (`checks`, `warnings`, and `errors`).

In order to confidently write interop tests that include VC verification, we need to more details about what these string arrays will contain. See #169 for some of the current testing being done.

**Comment by OR13** [comment]
I added a boolean... but we still need to discuss less terrible solutions

**Comment by OR13** [comment]
We discussed on the call, @BenjaminMoe @nissimsan  to propose a path forward, @brownoxford to recommend an approach.

blocked by lack of proposed solution.

**Comment by nissimsan** [comment]
@BenjaminMoe, let's discuss this tomorrow

**Comment by brownoxford** [comment]
Discussed on call. This is ready for PR, and suggested to bring this upstream to vc-api group.

**Comment by mkhraisha** [comment]
@msporny how do you feel about raising this issue/suggestion to the broader VC-API group

**Comment by msporny** [comment]
> @msporny how do you feel about raising this issue/suggestion to the broader VC-API group

Yep, +1 to that... we touched on this in the VC API group 3 weeks ago: https://github.com/w3c-ccg/vc-api/issues/292#issuecomment-1162360310

We got to these concrete next steps:

> PR needed: Define steps for verification at Verifier Service using normative language -- Check to make sure the structure of the VC is valid, check credentialSchema (if applicable), the verification method has not been revoked, check the credentialStatus has not been revoked

> PR needed: Create an issue marker to note that checking whether current time is between issuance date and expiration date is still up for debate wrt. whether that is a check that's done during verification or during validation.

> PR needed: Add options.eventLog (optional value), not mandatory, that provides the checks performed. By default that's turned off on successful verification. However, the eventLog is provided on failed verification.
