### ISSUE TITLE
Presentations prover should send VP in response body

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#188]
Right now, the API defines the responses for the `/presentations/prove` request as follows:

```
  responses:
    "201":
      description: Expected response to a valid request
      content:
        application/json:
          schema:
            $ref: "../schemas/SerializedVerifiableCredential.yml"
    default:
      $ref: "../responses/UnexpectedError.yml"
```

I believe this should reference `../schemas/SerializedVerifiablePresentation.yml`, not `../schemas/SerializedVerifiableCredential.yml`

@OR13 if you confirm I will fix immediately.

**Comment by OR13** [comment]
You are correct.

**Comment by TallTed** [comment]
I guess [this](https://github.com/w3c-ccg/traceability-interop/issues/188#issuecomment-1095182377) should have been an approving CODEOWNER review on [the PR](https://github.com/w3c-ccg/traceability-interop/pull/190)?
