### ISSUE TITLE
Add PR Preview for ReSpec

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#19]
Is it possible to use on CCG repos, so we can have PR previews.

See https://github.com/w3c-ccg/traceability-interop/pull/15#discussion_r650267057

**Comment by TallTed** [comment]
As I said in #15, I think @vsnt @wyc @kimdhamilton should be able to help with getting the necessary bits flipped, though I don't think they will work on existing PRs; I believe the previews will only get generated for PRs initiated after preview generation is turned on.

**Comment by OR13** [comment]
related: https://github.com/w3c/did-spec-registries/blob/main/ECHIDNA

https://github.com/w3c/did-spec-registries/blob/main/.travis.yml

**Comment by OR13** [comment]
related: https://github.com/w3c/did-spec-registries/pull/314/files

**Comment by mkhraisha** [comment]
> related: https://github.com/w3c/did-spec-registries/blob/main/ECHIDNA
> 
> https://github.com/w3c/did-spec-registries/blob/main/.travis.yml

I believe both of those links are broken.

**Comment by OR13** [comment]
discussed on the call, let me know if I can help set this up @mprorock

**Comment by mprorock** [comment]
since ECHIDNDA is up as open sources under MIT License I do not see any issues technically, however please see [FAQ](https://github.com/w3c/echidna/wiki/FAQ#can-i-publish-a-fpwd-with-echidna-a-rec) - Working Drafts appear to be fine based on that note - @w3c-ccg/chairs Any concerns from Wayne or Heather?

**Comment by vsnt** [comment]
LGTM @mprorock. Sounds like a good plan.

**Comment by mkhraisha** [comment]
@mprorock any updates on this? I believe @OR13 offered to help on this too.

**Comment by nissimsan** [comment]
@OR13 and @mprorock, would you action, pls?

**Comment by OR13** [comment]
@msporny how hard was it to setup https://github.com/w3c-ccg/vc-api/blob/main/.pr-preview.json ?

**Comment by msporny** [comment]
> @msporny how hard was it to setup https://github.com/w3c-ccg/vc-api/blob/main/.pr-preview.json ?

Install instructions here: https://github.com/tobie/pr-preview#install

**Comment by OR13** [comment]
This should be marked as ready for PR and picked up by someone who has time.

**Comment by OR13** [comment]
https://github.com/w3c-ccg/traceability-interop/blob/main/.pr-preview.json

**Comment by OR13** [comment]
I installed the "PR Preview App" for both repos.

**Comment by msporny** [comment]
> I tried but it was not enough, someone need to take another look.

I think I fixed it. I had to do the following things:

1. Re-enable PR Preview for all CCG repos -- someone changed it to only apply to the traceability repos.
2. Update "./docs/index.html" to "docs/index.html" in the .pr-preview.html file. 

Here's a test preview: https://github.com/w3c-ccg/traceability-interop/pull/86

**Comment by OR13** [comment]
@msporny you are a life saver.
