### ISSUE TITLE
Do we need to be more specific about using did document `service` array?

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#193]
Our tests are now using DID document `service` array to get base url for presentation verifier (see #182, #183, #191).

We are blindly using `services[0].serviceEndpoint` for this purpose - should we not instead filter that list for a service with DID URL having `#traceability-api` fragment or `type:"TraceabilityAPI"`?

**Comment by mkhraisha** [comment]
`type:"TraceabilityAPI"` resonates quite a bit

**Comment by OR13** [comment]
Also fix the todo noted on https://github.com/w3c-ccg/traceability-interop/pull/191#issuecomment-1095234699

**Comment by brownoxford** [comment]
I think we can close this now that PRs have been merged.
