### ISSUE TITLE
Define Universal Wallet objects for presentation submissions in the universal wallet interop spec

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#2]
This proposal was made originally to link the VC Data Model and Universal Wallet and VC HTTP APIs, together in a way that would support interoperability across HTTP based wallets:

https://github.com/OR13/simple-presentations

We should discuss the associated assumed JSON models related to "handling presentations", including preserving of metadata etc...

Since this work is related to a number of active CCG work items, we may need to cross link here to provide sufficient context.

**Comment by OR13** [comment]
An alternative to preserving the "challenge" is "issuing a challenge token from the verifier"... that can then be verified instead of looked up...

this approach is taken in https://github.com/decentralized-identity/waci-presentation-exchange

**Comment by OR13** [comment]
Feels like we have answered this question, by saying: "anyone can present anything"

... for now.


Noting that this is different than the authorization strategy for the channel... this is:

"Can this holder present these credentials"... or  "is this holder presenting credentials that I expect them too"

**Comment by OR13** [comment]
Leave this open until we can untangle the "VP" authorization vs "HTTP" authorization issues.

**Comment by OR13** [comment]
@OR13 to retitle the issue and provide concrete examples of what we mean.

**Comment by nissimsan** [comment]
I can make an example for this to make it more tangible

**Comment by TallTed** [comment]
I don't grok the question.  The other repos don't help me much.  Maybe the relevant chunks of those other pages could be brought inline to the question, and some meat added to the question itself?

**Comment by OR13** [comment]
@nissimsan

**Comment by mkhraisha** [comment]
Discussed on Aug 24 call, @nissimsan  to provide examples

**Comment by nissimsan** [comment]
Incorrect interpretation: 
How does a holder acting like a verifier store their data structure. 
CCG doesn't bother with this, universal wallet does. Meta data should include: who presented, when did I store it. 
Seems not relevant for this group.

**Comment by nissimsan** [comment]
To be closed.

**Comment by OR13** [comment]
We can't actually enforce this.

**Comment by TallTed** [comment]
Out of scope, because we can't enforce.  (Might be fodder for a Best Practices doc.)
