### ISSUE TITLE
need static test reporting

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-interop#200]
need to add in static html reporting via pr #177 and publish to gh-pages

**Comment by OR13** [comment]
We do not currently support the nice report visualization, and the readme does not contain a link to it.

This ticket can be closed when the readme contains a link to the nice report. and the nice report is run nightly.

**Comment by mkhraisha** [comment]
@mprorock assigning you to this

**Comment by brownoxford** [comment]
This has been finished and integrated into `main`. Static interactive reports are now generated nightly.

**Comment by OR13** [comment]
This is amazing... https://w3id.org/traceability/interoperability/reports

**Comment by OR13** [comment]
closing.
