### ISSUE TITLE
Deleting all workflows except  CI and Report Generation

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-interop#201]
Unless there's a need to run workflows individually, we should get rid of the ones which aren't CI or Generate the interop report. 

Only the .yml should be deleted, not the postman collection. 

We discussed this [here](https://github.com/w3c-ccg/traceability-interop/pull/167), but is was proposed that get rid of more than the three proposed deletions.

**Comment by brownoxford** [comment]
Here is the list of current workflow YAML files that we have agreed to keep outright:

- interoperability-report.yml (Interop tests and publication of results)
- publish-openapi-spec.yml (Build and publish OpenAPI spec on changes)
- ci.yml.skip (Runs linter, possibly disabled currently)

The following all run various unit testing workflows, with cross-provider matrices where appropriate.

- authentication-tutorial.yml
- regression-agility.yml
- regression-credentials-issue.yml
- regression-credentials-verify.yml
- regression-did-web-discovery.yml
- regression-mtrc.yml
- regression-presentations-exchange.yml
- regression-presentations-verify.yml
- regression-vc-jwt.yml
- regression-workflow-instance-join.yml

@mprorock suggested that it could be beneficial to have these available for manual `workflow_dispatch`.

Let's continue the discussion here.

**Comment by OR13** [comment]
i suggest we keep workflows dispatched individually, because thats useful for testing and tutorials.

**Comment by OR13** [comment]
I suggest we remove any workflow that is not useful for testing or tutorials, or that is redundant and complex.

**Comment by nissimsan** [comment]
This is only about clearing out the list on https://github.com/w3c-ccg/traceability-interop/actions
