### ISSUE TITLE
RESOLVED: One of the authorization protocols that will be defined for use in the VC-HTTP-API MUST be OAuth 2 Client Credentials.

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#21]
RESOLVED: One of the authorization protocols that will be defined for use in the VC-HTTP-API MUST be OAuth 2 Client Credentials.

^ from the call, we should note this is a normative requirement.

**Comment by TallTed** [comment]
The title is misleading, suggesting that OAuth 2 Client Credentials will be the *only* authz protocol.  The opening comment shows what we actually resolved, and should be accurately reflected in the title of the issue.

**Comment by OR13** [comment]
agreed to keep this open, until we can point to it in their spec.

**Comment by mkhraisha** [comment]
We need to clarify if this is based on the VC-HTTP-API resolutions or if this is an internal trace interop resolution

**Comment by mkhraisha** [comment]
PROPOSAL: One of the authorization protocols that will be defined for use in the trace interop profile for the VC-HTTP-API MUST be OAuth 2 Client Credentials.

**Comment by mkhraisha** [comment]
Can someone post a link to where this resolution was resolved? if not we can run it in the trace interop call.

**Comment by nissimsan** [comment]
@OR13, is this RESOLVE or RESOLVED? If the latter, can you provide a link, pls?

**Comment by OR13** [comment]
This can be closed as soon as https://github.com/w3c-ccg/traceability-interop/pull/35 is confirmed to be running in secure mode only.

I think we are close, but still security may not yet be required.

**Comment by OR13** [comment]
Better tracked in https://github.com/w3c-ccg/traceability-interop/issues/34

**Comment by nissimsan** [comment]
Closing, continue tracking on #34
