### ISSUE TITLE
Abstract and Introduction contradict

### ISSUE THREAD

**Issue by brianorwhatever** [w3c-ccg/traceability-interop#22]
The abstract talks about this being a vocab and the introduction talks about this being a platform. The abstract can probably be written at a later date and we can track that here

**Comment by mkhraisha** [comment]
* Abstract needs to be rewritten
* Introduction needs to be rewritten
* Terminology needs to be expanded on
* Use Cases and Requirements needs to be revisited first
* Revision OAUTH and client credentials according to agreed upon proposal
* Presentation Exchange should be under use cases if we're keeping it
* Section 5 needs to be cleaned up and reference section 3

**Comment by nissimsan** [comment]
I can take a stab at this.

**Comment by nissimsan** [comment]
- [ ] Abstract needs to be rewritten
- [ ] Introduction needs to be rewritten
- [ ] Terminology needs to be expanded on
- [ ] Use Cases and Requirements needs to be revisited first
- [ ] Revision OAUTH and client credentials according to agreed upon proposal
- [ ] Presentation Exchange should be under use cases if we're keeping it
- [ ] Section 5 needs to be cleaned up and reference section 3

**Comment by nissimsan** [comment]
On Use Cases and Reqs, we need to link to the VC-API.

**Comment by mkhraisha** [comment]
https://w3c-ccg.github.io/vc-api-use-cases/

**Comment by nissimsan** [comment]
@mkhraisha  to open separate issues for remaining open points.

**Comment by mkhraisha** [comment]
@nissimsan i created https://github.com/w3c-ccg/traceability-interop/issues/27 to track terminology, also if you can link to #21 for the OAUTH section. 
Presentation exchange and section 5/3 should just be tracked here I believe as they don't appear to need their own issues.

**Comment by nissimsan** [comment]
Auth: 
https://w3c-ccg.github.io/traceability-interop/#authorization

**Comment by nissimsan** [comment]
Let's run through this when @mkhraisha 's on the call and make sure everything is covered. Then we can probably close this.

**Comment by mkhraisha** [comment]
This has been covered in other issues, closing
