### ISSUE TITLE
Discuss and clarify use of "Issuer" and "Verifier" in tests

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#225]
Current multi-party presentation tests (`presentations-exchange` and `presentations-verify`) use the terms `Issuer` and `Verifier` to represent multiple parties in the tests.

In both cases, the flow includes the following relevant items:

- A call is made to the `Issuer` to issue a credential
- The credential is stored in the Postman collection variables, making the test runner sort of act as a `Holder`
- A call is made to the `Verifier` to initiate the presentation exchange
- A call is made to the `Issuer` to sign the presentation
- A call is made to the `Verifier` to complete the presentation exchange
- In the case of the `presentations-verify` test, a last call to the `Verifier` is made to verify the presentation

There are, or could be, some issues with the use of these well-known terms improperly in these tests. This issue has been created to discuss their use to determine whether we need to modify them or if additional documentation would suffice to prevent confusion for folks who are already very familiar with `Issuer`/`Holder`/`Verifier` semantics.

**Comment by nissimsan** [comment]
> "making the test runner sort of act as a Holder"

> "the holder is basically the test runner today"

I don't quite agree with these ^ statements. The runner represents not only the holder, but _all_ involved roles, switching between them, invoking corresponding endpoints; often also switching platform provider. 

Example:
- Runner acts as party A in the role of `issuer`, calling `/credentials/issue` on mesur
- Runner acts as party A in the role of `holder`, calling `/presentations/available` on Transmute
- Runner acts as party A in the role of `holder`, calling `/presentations/prove` on mesur
- Runner acts as party A in the role of `holder`, calling `/presentations/submissions` on Transmute
- Runner acts as party B in the role of `verifier`, calling `/credentials/verify` on Transmute

I very much agree with the premise of this issue. This is a difficult message to communicate. I would suggest a section on the trace-interop respec page which introduces this.

**Comment by nissimsan** [comment]
Gave this a shot: #231
