### ISSUE TITLE
Remove Presentation Exchange test in report

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c-ccg/traceability-interop#234]
It looks like the `presentation-exchange` test has been replaced by other tests and no longer needs to be in the report. Ref: https://github.com/w3c-ccg/traceability-interop/pull/233#discussion_r877186170

>This entire test can be removed. We are already ensuring that alsoknownAs is present in another test, and this one exists solely to persist the issuer id. This is actually a copy/paste error and the test should have been using credential_verifier_id, but since we never use that value anywhere, we can just remove this test.

**Comment by brownoxford** [comment]
Please note that this refers ONLY to the single test that was (prior to #233) persisting the `credential_issuer_id` in the collection variables. After the merge of PR #233, the test in question now looks like the following code block, and can be removed from the Tests tab of the "Get Organization DIDs (Verifier)" request in the "Presentation Exchange Tutorial":

```
// The value of didDocument.alsoKnownAs[1] is persisted as a Postman collection
// variable that can be accessed by other requests in the collection by calling
// pm.collectionVariables.get("credential_issuer_id").
pm.test("`credential_issuer_id` persisted to collectionVariables", function() {
    const { alsoKnownAs } = pm.response.json().didDocument;
});
```
