### ISSUE TITLE
Adding a couple of more traceability Jitsi hosts, pls? 

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-interop#240]
Hi @msporny, 

On the traceability call today I asked if we could add myself (nis@transmute.industries) and Ben (benjamin@transmute.industries) as hosts so we can start the Tuesday traceabiliity jitsi calls. @mkhraisha said I should ask you about it - is that something you can help us with, please? 

Hope you're doing good! Say hi to your team from me, pls. :)

Nis

**Comment by nissimsan** [comment]
@mprorock copying you on this ^^

Plus @OR13

**Comment by nissimsan** [comment]
@mprorock - ping, pls?

**Comment by msporny** [comment]
> On the traceability call today I asked if we could add myself ([nis@transmute.industries](mailto:nis@transmute.industries)) and Ben ([benjamin@transmute.industries](mailto:benjamin@transmute.industries)) as hosts so we can start the Tuesday traceabiliity jitsi calls. @mkhraisha said I should ask you about it - is that something you can help us with, please?

Hey, @nissimsan -- apologies, looks like this request got devoured by my inbox. Yes, happy to... creating accounts now.

**Comment by msporny** [comment]
@nissimsan accounts created, you have the login details now. Same for Benjamin.

Let me know if you guys need to know how to log in... it's in the "..." menu, I believe... under "Settings->Profile" IIRC -- it's in a weird place... but once you log in, you should see a crown next to your icon.

> Hope you're doing good! Say hi to your team from me, pls. :)

Yes, doing well... hope you're well too! Hoping to catch up with you if there is ever an event in EU that you're going to -- RWoT is in The Hague in September IIRC, don't know if you're going?

I've sent your message to the team, I know they'll love to see that you said hi. :)

**Comment by brownoxford** [comment]
@msporny can you add me as well please?

**Comment by msporny** [comment]
> @msporny can you add me as well please?

Done.

**Comment by brownoxford** [comment]
Everyone who needed adding has been added, we can close this out now.
