### ISSUE TITLE
Define OAuth2 requirements for `/presentations/available`

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#243]
The goal of this issue is start discussion regarding the OAuth2 authentication requirements of the [`/presentations/available` endpoint](https://w3c-ccg.github.io/traceability-interop/openapi/#post-/presentations/available).  This issue stems from the discussion on #187, and can be considered complete when the following items are resolved:

_**Please note**: the following lists are displayed as GitHub task lists for visual effect, not to suggest that there are actually additional tasks to be done._

The state of the checkboxes in this description represent the in-progress resolution of this issue. Until the `ready-for-close` label is applied, this issue should be considered in-progress. __This issue `MUST NOT` be closed until corresponding issues have been opened to implement the relevant conformance testing and, if necessary, modify the openapi spec.__

**Goal 1: Explicitly state OAuth2 requirements for the `/presentations/available` endpoint**
_One, and only one, of these options `MUST` be selected._

- [ ] The `/presentations/available` endpoint MAY require OAuth2
- [ ] The `/presentations/available` endpoint MUST require OAuth2
- [x] The `/presentations/available` endpoint MUST NOT require OAuth2

**Goal 2: Explicitly define scope requirements for this endpoint when authentication is in use:**
_One or more of these options `MUST` be selected **unless** the `MUST NOT` option was selected in **Goal 1**, in which case these options `MUST NOT` be selected. For requests that require OAuth2, each of the selected scopes `MUST` be present in an OAuth2 bearer token in order for the request to be permitted._

The following list of OAuth2 scopes is pulled from the current `openapi.yaml` file. If additional scopes are needed for the `/presentations/available` endpoint, they should be added here and an issue should be created to ensure that `openapi.yaml` is updated.
- [ ] `resolve:dids`
- [ ] `issue:credentials`
- [ ] `verify:credentials`
- [ ] `read:credentials`
- [ ] `update:credentials`
- [ ] `prove:presentations`
- [ ] `verify:presentations`
- [ ] `submit:presentations`

**Comment by BenjaminMoe** [comment]
**Goal 1:**

The `/presentations/available` endpoint MUST NOT require OAuth2

**Comment by nissimsan** [comment]
> The /presentations/available endpoint MUST NOT require OAuth2

+1 on this. 

This is a DIDAuth endpoint. OAuth on top of it would be double-authentication.

**Comment by brownoxford** [comment]
OpenAPI documentation has been updated. Since OAuth2 is not required for this endpoint, we will not need to write specific negative testing to ensure that it is enabled. This can be closed out.

**Comment by nissimsan** [comment]
We did this.
