### ISSUE TITLE
Define OAuth2 requirements for `/presentations/verify`

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#244]
The goal of this issue is start discussion regarding the OAuth2 authentication requirements of the [`/presentations/verify` endpoint](https://w3c-ccg.github.io/traceability-interop/openapi/#post-/presentations/verify).  This issue stems from the discussion on #187, and can be considered complete when the following items are resolved:

_**Please note**: the following lists are displayed as GitHub task lists for visual effect, not to suggest that there are actually additional tasks to be done._

The state of the checkboxes in this description represent the in-progress resolution of this issue. Until the `ready-for-close` label is applied, this issue should be considered in-progress. __This issue `MUST NOT` be closed until corresponding issues have been opened to implement the relevant conformance testing and, if necessary, modify the openapi spec.__

**Goal 1: Explicitly state OAuth2 requirements for the `/presentations/verify` endpoint**
_One, and only one, of these options `MUST` be selected._

- [ ] The `/presentations/verify` endpoint MAY require OAuth2
- [x] The `/presentations/verify` endpoint MUST require OAuth2
- [ ] The `/presentations/verify` endpoint MUST NOT require OAuth2

**Goal 2: Explicitly define scope requirements for this endpoint when authentication is in use:**
_One or more of these options `MUST` be selected **unless** the `MUST NOT` option was selected in **Goal 1**, in which case these options `MUST NOT` be selected. For requests that require OAuth2, each of the selected scopes `MUST` be present in an OAuth2 bearer token in order for the request to be permitted._

The following list of OAuth2 scopes is pulled from the current `openapi.yaml` file. If additional scopes are needed for the `/presentations/verify` endpoint, they should be added here and an issue should be created to ensure that `openapi.yaml` is updated.
- [ ] `resolve:dids`
- [ ] `issue:credentials`
- [ ] `verify:credentials`
- [ ] `read:credentials`
- [ ] `update:credentials`
- [ ] `prove:presentations`
- [x] `verify:presentations`
- [ ] `submit:presentations`

**Comment by BenjaminMoe** [comment]
**Goal 1:**

The `/presentations/verify` endpoint MUST require OAuth2

**Goal 2:**

`verify:credentials` Grants permission verify Verifiable Credentials

**Opinion:**

The verify credential doesn't necessarily require the user to be logged in to verify a credential. So it's potentially possible to host the verify operation as a public service. But in practicality the verify operation is fairly expensive in terms of computational power, so in practically you would want to require OAuth for this end point.

**Comment by TallTed** [comment]
Why MUST it require OAuth2?  Why is no other (possibly not yet existent) authentication method viable?

(I strongly advise not treating "OAuth" and "OAuth2" as interchangeable terms, i.e., if an "endpoint MUST require OAuth2", it doesn't make sense "to require OAuth for this end point".)

**Comment by brownoxford** [comment]
Should the required scope here be `verify:presentations`?

**Comment by brownoxford** [comment]
OpenAPI documentation has been updated, and conformance tests are in place. This can be closed out.

**Comment by nissimsan** [comment]
We did this.
