### ISSUE TITLE
Define OAuth2 requirements for `/presentations`

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#246]
The goal of this issue is start discussion regarding the OAuth2 authentication requirements of the [`/presentations` endpoint](https://w3c-ccg.github.io/traceability-interop/openapi/#post-/presentations).  This issue stems from the discussion on #187, and can be considered complete when the following items are resolved:

_**Please note**: the following lists are displayed as GitHub task lists for visual effect, not to suggest that there are actually additional tasks to be done._

The state of the checkboxes in this description represent the in-progress resolution of this issue. Until the `ready-for-close` label is applied, this issue should be considered in-progress. __This issue `MUST NOT` be closed until corresponding issues have been opened to implement the relevant conformance testing and, if necessary, modify the openapi spec.__

**Goal 1: Explicitly state OAuth2 requirements for the `/presentations` endpoint**
_One, and only one, of these options `MUST` be selected._

- [ ] The `/presentations` endpoint MAY require OAuth2
- [x] The `/presentations` endpoint MUST require OAuth2
- [ ] The `/presentations` endpoint MUST NOT require OAuth2

**Goal 2: Explicitly define scope requirements for this endpoint when authentication is in use:**
_One or more of these options `MUST` be selected **unless** the `MUST NOT` option was selected in **Goal 1**, in which case these options `MUST NOT` be selected. For requests that require OAuth2, each of the selected scopes `MUST` be present in an OAuth2 bearer token in order for the request to be permitted._

The following list of OAuth2 scopes is pulled from the current `openapi.yaml` file. If additional scopes are needed for the `/presentations` endpoint, they should be added here and an issue should be created to ensure that `openapi.yaml` is updated.
- [ ] `resolve:dids`
- [ ] `issue:credentials`
- [ ] `verify:credentials`
- [ ] `read:credentials`
- [ ] `update:credentials`
- [ ] `prove:presentations`
- [ ] `verify:presentations`
- [x] `submit:presentations`

**Comment by BenjaminMoe** [comment]
**Goal 1:**

The `/presentations` endpoint MUST require OAuth2

**Goal 2**;

`submit:presentations` Grants permission to submit Verifiable Presentations

**Opinion**:

This one should be non-ambiguous, requires OAuth by definition.

**Comment by BenjaminMoe** [comment]
>Where's the definition that mandates OAuth (or OAuth2)?

This was a mistype on my end. Where I used OAuth as a general term. The standard industry version of OAuth is OAuth2. I updated my comment to specify OAuth2.

**Comment by TallTed** [comment]
OK, where's the definition of `submit:presentations` wherein it "requires OAuth2 by definition"?

If I'm reading things correctly, I *think* that should be in `openapi.yaml`, but so far as I can tell, there's no such file in this repo, so at minimum, there should be a link out to it in this (and every other) issue that refers to it.

**Comment by brownoxford** [comment]
> so far as I can tell, there's no such file in this repo

Hi Ted, the `openapi.yml` file is located at `docs/openapi/openapi.yml`, but the spec is denormalized into a number of files under the `docs/openapi` folder for development purposes, i.e., not easily usable for reference. There is a nightly automated job that compiles those files into a user-friendly web based version of that document which is deployed to https://w3c-ccg.github.io/traceability-interop/openapi/. The link to this documentation can always be found in the ["Latest Spec" section of the repository README.md file](https://github.com/w3c-ccg/traceability-interop#latest-spec).

I also want to clarify the difference between the endpoint path `/presentations`, and the OAuth2 scope `submit:presentations`. The path is the relevant part of the API URL that an end-user would access in order to use the API functionality for, in this case, presenting a verifiable presentation. When discussing the various endpoints as we are here, the rest of the URL (scheme, host, path prefix, etc.) is generally not necessary to include. The `submit:presentations` OAuth2 scope is one of possibly several scopes that are embedded in the OAuth2 token. These scopes serve to indicate what the holder of the token is permitted to do, and an API with multiple endpoints will typically review those scopes when determining whether to allow or deny access to an endpoint. This is an indirection that is useful when you want to allow client applications to use part of your api but not all of it. If you didn't use scopes, you would need to validate client access to endpoints per-client; this would require code changes for every new client or access change. With scopes, you can simply add or remove scopes from clients without modifying your code.

I hope I've done a good job of explaining scopes. If not, please feel free to reach out.

The definition that you are looking for is located in the [Presentations section](https://w3c-ccg.github.io/traceability-interop/openapi/#post-/presentations) of that spec document, which indicates that an OAuth2 token with `submit:presentations` scope is required when accessing the `/presentations` endpoint.

![Screen Shot 2022-06-15 at 5 24 51 PM](https://user-images.githubusercontent.com/755209/173932633-a0ef29d7-f85c-43ec-af60-ab719236841b.png)

All that being said, I think the purpose of these issues is to foster some discussion and come to a conclusion about the authentication requirements of each of the endpoints so that we can make any necessary spec changes and put this issue behind us.

**Comment by BenjaminMoe** [comment]
> OK, where's the definition of `submit:presentations` wherein it "requires OAuth2 by definition"?

The definition of the end-point is described in this comment: https://github.com/w3c-ccg/traceability-interop/issues/242#issuecomment-1156846715

Once it's established that OAuth2 is required, the next step is to identify which scope name is to be assigned to the end-point. In this case that scope name as been assigned as `submit:presentations`.

**Comment by nissimsan** [comment]
`/presentations` is the Oauth2 alternative to the DIDAuth endpoints (`/available` and `/submissions`). 

+1 on https://github.com/w3c-ccg/traceability-interop/issues/246#issuecomment-1155538126. Although I would word it this way: 

- **The `/presentations` endpoint MUST require OAuth2**
- **`submit:presentations` MUST grant permission to invoke `/presentations`**

**Comment by brownoxford** [comment]
> * `submit:presentations` MUST grant permission to invoke `/presentations`

I would counter that multiple scopes _could_ be required to access and endpoint, and this language indicates that a single one is sufficient. In most of our use cases I think that is correct, but semantically I don't think a `MUST` and all of its associated meaning can be used here.

I concede that the descriptive text next to the scopes is a bit confusing, perhaps we should simply remove it from these issues? I have also added a short text clarifying *Goal 2*:

_One or more of these options MUST be selected unless the MUST NOT option was selected in Goal 1, in which case these options MUST NOT be selected._

**Comment by TallTed** [comment]
Perhaps --

* `submit:presentations` MUST grant permission to invoke `/presentations`. Specific deployments MAY require additional scopes without which `/presentations` invocation MAY be rejected.

**Comment by brownoxford** [comment]
@TallTed those seem contradictory to me.

**Comment by TallTed** [comment]
@brownoxford -- To me, it seems that the permission granted by `submit:presentations` may be insufficient on its own; that there are other scopes which may also be required.  This does not seem contradictory to me.

**Comment by nissimsan** [comment]
Confirming this is defined on the OAS already. No changed needed there.
https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/resources/presentations.yml#L8

**Comment by brownoxford** [comment]
OpenAPI documentation has been updated, and conformance tests are in place. This can be closed out.

**Comment by nissimsan** [comment]
We did this.
