### ISSUE TITLE
Define OAuth2 requirements for `/credentials/:credential-id`

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#247]
The goal of this issue is start discussion regarding the OAuth2 authentication requirements of the [`/credentials/:credential-id` endpoint](https://w3c-ccg.github.io/traceability-interop/openapi/#get-/credentials/-credential-id-).  This issue stems from the discussion on #187, and can be considered complete when the following items are resolved:

_**Please note**: the following lists are displayed as GitHub task lists for visual effect, not to suggest that there are actually additional tasks to be done._

The state of the checkboxes in this description represent the in-progress resolution of this issue. Until the `ready-for-close` label is applied, this issue should be considered in-progress. __This issue `MUST NOT` be closed until corresponding issues have been opened to implement the relevant conformance testing and, if necessary, modify the openapi spec.__

**Goal 1: Explicitly state OAuth2 requirements for the `/credentials/:credential-id` endpoint**
_One, and only one, of these options `MUST` be selected._

- [x] The `/credentials/:credential-id` endpoint MAY require OAuth2
- [ ] The `/credentials/:credential-id` endpoint MUST require OAuth2
- [ ] The `/credentials/:credential-id` endpoint MUST NOT require OAuth2

**Goal 2: Explicitly define scope requirements for this endpoint when authentication is in use:**
_One or more of these options `MUST` be selected **unless** the `MUST NOT` option was selected in **Goal 1**, in which case these options `MUST NOT` be selected. For requests that require OAuth2, each of the selected scopes `MUST` be present in an OAuth2 bearer token in order for the request to be permitted._

The following list of OAuth2 scopes is pulled from the current `openapi.yaml` file. If additional scopes are needed for the `/credentials/:credential-id` endpoint, they should be added here and an issue should be created to ensure that `openapi.yaml` is updated.
- [ ] `resolve:dids`
- [ ] `issue:credentials`
- [ ] `verify:credentials`
- [x] `read:credentials`
- [ ] `update:credentials`
- [ ] `prove:presentations`
- [ ] `verify:presentations`
- [ ] `submit:presentations`

**Comment by brownoxford** [comment]
The `/credentials/:credential-id` endpoint MUST require OAuth2 to ensure that only authorized requests are allowed.

**Comment by BenjaminMoe** [comment]
Require OAuth2 for credentials that are not public.
No authentication required for credentials that are public.

**Comment by mkhraisha** [comment]
Who defines if a credential is public or not?

**Comment by mprorock** [comment]
hard must for us - any retrieval of credentials MUST be authenticated and authorized - VC-API may have some public credential use cases, but I am not aware of any public facing cases that would apply here

**Comment by TallTed** [comment]
> [@brownoxford] The `/credentials/:credential-id` endpoint MUST require OAuth2 to ensure that only authorized requests are allowed.

Requiring the endpoint to *support* OAuth2 is reasonable to me, but requiring that OAuth2 be *used* is not.

> [@BenjaminMoe] Require OAuth2 for credentials that are not public. 
> OAuth2 not required for credentials that are public.

Exactly.

> [@mkhraisha] Who defines if a credential is public or not? and how do they do that?

Deployer, administrator, etc., defines whether a credential is public or private, and if private, available to what entities as authenticated via OAuth2.

> [@mprorock] hard must for us - any retrieval of credentials MUST be authenticated and authorized

Sure. That's _business logic_ a/k/a _use case-specific_ a/k/a _deployment/admin decision_.

**Comment by brownoxford** [comment]
I do think it is worth pointing out again that if this is defined as `MUST` and an implementor decides not to require OAuth2, they will fail conformance testing but not interoperability testing.

**Comment by TallTed** [comment]
> I do think it is worth pointing out again that if this is defined as `MUST` and an implementor decides not to require OAuth2, they will fail conformance testing but not interoperability testing.

And as I a=said before... "Requiring [a conforming] endpoint to _support_ OAuth2 is reasonable to me, but requiring that OAuth2 be _used_ [in all scenarios] is not."

If the deploying user/administrator determines that some endpoint (or some resource/s accessible thereby) is *public* a/k/a unprotected a/k/a not requiring of authn/authz, it is unreasonable to require them to take whatever steps are needed to get the OAuth2 feature to work on that endpoint.

**Comment by brownoxford** [comment]
I'm not sure that we will be able to write OAuth2 conformance tests for this endpoint if this is a `MAY` (please help me out here if I'm wrong).

`MUST NOT` tests can be written to confirm that an endpoint **is** accessible without a bearer token.

`MUST` Tests can be written to confirm that an endpoint **is not** accessible without a bearer token

Unless we require implementors to pre-seed their credentials with a known ID that corresponds to a revocation credential, there doesn't seem to be a way to test both conditions. Do we need to consider the addition of a `/credentials/revocation/:credential-id` endpoint?

Am I missing something obvious?

**Comment by BenjaminMoe** [comment]
I think the conformance test would effectively be something like the following flow.

1. I issue a revocable credential
2. The revocable credential has a reference to the revocation list
3. I CAN access the credential issues in [1] WITH an access token
4. I CANNOT access the credential issues in [1] WITHOUT an access token
5. I CAN access the revocation list referenced from [1] WITH an access token
6. I CAN access the revocation list referenced from [1] WITH an access token

**Comment by TallTed** [comment]
Going in the right direction.

> 3. I CAN access the credential issues in [1] WITH an bearer token
> 4. I CANNOT access the credential issues in [1] WITHOUT an bearer token

I think the instances of "credential issue***s***" in these should be "credential issue***d***".
