### ISSUE TITLE
add html tidy or other HTML linting/formatting as part of build process

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-interop#25]
need to make sure HTML is clean and properly formatted before PRs go out etc

**Comment by mprorock** [comment]
nb: we do not yet have a build process on this doc, so will likely need to add in lerna or similar as is done in trace-vocab:
e.g. [package.json](https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/traceability-schemas/package.json)

**Comment by nissimsan** [comment]
@mkhraisha to run with this.

**Comment by mkhraisha** [comment]
i'll take care of this

**Comment by OR13** [comment]
might want to look at husky and commit hooks for this

**Comment by nissimsan** [comment]
Will this make contributions harder? Filter out supply chain experts which aren't comfortable running LINT scripts?

**Comment by nissimsan** [comment]
@mkhraisha's PR fixes this. Will be cleaned up this week.

**Comment by OR13** [comment]
we did it.
