### ISSUE TITLE
Integrate new conformance tests with existing testing/reporting

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#265]
Output from the new conformance testing suite should be integrated into the existing testing and reporting setup.

**Comment by OR13** [comment]
Does this apply to both "raw reports" and "interoperability report" ?

**Comment by brownoxford** [comment]
Yes, this applies both to the interactive "interoperability report" as well as to the raw output `.json` and `.html` files on which it depends. If new badges or links make sense to add, then they should be added as part of the work on this issue.
