### ISSUE TITLE
Terminology needs to be expanded in the Spec

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-interop#27]
The terminology section of the spec needs to be expanded on, as it is currently pretty barren.

**Comment by OR13** [comment]
Example of how to cite terms defined in other specs: https://github.com/decentralized-identity/JWS-Test-Suite/blob/main/data/index.html#L154

**Comment by nissimsan** [comment]
@mkhraisha to link to trace-vocab, adding missing parts. 
(Not for next week though)

**Comment by OR13** [comment]
seems a bit of a dupe of the trace-vocab related item.

seems like we need to define security terms related to interop profile.
