### ISSUE TITLE
Update templates used for reporting

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#272]
Current interoperability and conformance test reports are generated using the same HTML template. Determine whether or not it makes sense to use separate templates and, if so, modify the templates as needed to be report-specific.

**Comment by BenjaminMoe** [comment]
Interop Report: https://w3c-ccg.github.io/traceability-interop/reports/interoperability/
Conformance Report: https://w3c-ccg.github.io/traceability-interop/reports/conformance/

Possible suggestions change title or summary.

**Comment by BenjaminMoe** [comment]
Change title and summary.
