### ISSUE TITLE
Schema definition for DID Document @context needs updating

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#282]
The current Open API schema in [TraceabilityAPIDIDWebDocument.yml](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/TraceabilityAPIDIDWebDocument.yml#L4,L7) defines `@context` to be a string array.

This is problematic, because it does not allow for expanded term definitions, which causes responses making use of `@vocab` to fail validation, e.g., the following fails validation with the message `response validates against schema | AssertionError: expected data to satisfy schema but found following errors: data['@context'][2] should be string`
```
    "@context": [
        "https://www.w3.org/ns/did/v1",
        "https://w3id.org/security/suites/jws-2020/v1",
        {
            "@id": "https://www.w3.org/ns/did/#",
            "@type": "@vocab"
        }
    ],
```

A possible change represented in json-schema is:

```
    "@context": {
    "oneOf": [
      {
        "type": "string",
        "pattern": "^https://(w3id.org|www.w3.org/ns)/did/v1$"
      },
      {
        "type": "array",
        "items": [
          {
            "type": "string",
            "pattern": "^https://(w3id.org|www.w3.org/ns)/did/v1$"
          }
        ],
        "uniqueItems": true,
        "additionalItems": {
          "oneOf": [
            {
              "type": "object"
            },
            {
              "type": "string"
            }
          ]
        }
      }
    ]
```

**Comment by TallTed** [comment]
@brownoxford — `data['@context'][2]` either needs the single-quotes replaced by backticks (i.e., ```[`@context`][2]```) or backticks added inside the single-quotes (i.e., ```['`@context`'][2]```) ...

**Comment by brownoxford** [comment]
doh. thanks @TallTed, comment updated.

**Comment by brownoxford** [comment]
According to [did-core](https://www.w3.org/TR/did-core/#json-ld),

> The [JSON-LD Context](https://www.w3.org/TR/json-ld11/#the-context) is either a [string](https://infra.spec.whatwg.org/#string) or a [list](https://infra.spec.whatwg.org/#list) containing any combination of [strings](https://infra.spec.whatwg.org/#string) and/or [ordered maps](https://infra.spec.whatwg.org/#maps).

**Comment by brownoxford** [comment]
Note that OAS v3.0 does not support the `additionalItems` JSON Schema keyword, so we are limited to type checking here.
