### ISSUE TITLE
`/identifiers/:did` spec may require additional responses

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#289]
The OAS document currently does not specify any type of expected error for invalid `:did` arguments, and instead falls back to a default "unexpected" error defined in [UnexpectedError.yml](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/responses/UnexpectedError.yml)

Questions:
* What is the expected response when the provided `:did` parameter is not a valid DID?
* What is the expected response when the provided `:did` cannot be resolved?

If the answer to either of these questions is something other than the current behavior, we will need to make changes to both the OAS and the conformance suite.

**Comment by nissimsan** [comment]
Some kinds of 4XX error should be returned.

**Comment by OR13** [comment]
See https://w3c.github.io/did-spec-registries/#did-resolution-metadata

Suggest http status code and messages that align.

**Comment by brownoxford** [comment]
If the provided value for `:did` is not a valid DID, the response `code` should be `400` (Bad Request) with a message of `Bad Request: Invalid DID`

If the provided value for `:did` cannot be resolved, the response `code` should be `404` (Not Found) with a message of `Not Found: The requested resource could not be found`
