### ISSUE TITLE
Section Required on  "Ethical, Privacy, Human Rights, and Related Considerations"

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-interop#29]
We need to add a section in the spec on  "Ethical, Privacy, Human Rights, and Related Considerations":

Probably replacement for the privacy considerations.

**Comment by OR13** [comment]
Add a link to https://w3ctag.github.io/ethical-web-principles/

**Comment by mkhraisha** [comment]
@mprorock I believe we discussed you wanted to have some input here

**Comment by mprorock** [comment]
see PR #47

**Comment by OR13** [comment]
This was done.
