### ISSUE TITLE
Presentation Exchange OAuth is missing a readme file

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c-ccg/traceability-interop#307]
All of the other tutorials have a top-level readme file which describes the postman collection. Presentation Exchange OAuth only has the postman .json file. https://github.com/w3c-ccg/traceability-interop/tree/main/docs/tutorials/presentations-exchange-oauth

**Comment by nissimsan** [comment]
Given that this is the direction we agree on going (switching from DIDAuth to Oauth), this is a particularly important tutorial to add.

**Comment by brownoxford** [comment]
I have not been able to work on this tutorial yet.

**Comment by brownoxford** [comment]
No work as of yet, conformance testing has been taking higher priority.

**Comment by BenjaminMoe** [comment]
I'll make a ticket to review and work on this.

**Comment by nissimsan** [comment]
@BenjaminMoe  to work on this.

**Comment by OR13** [comment]
We still need to create a readme for this.

**Comment by BenjaminMoe** [comment]
Closing as done.
