### ISSUE TITLE
/presentations endpoints support for TraceablePresentations 

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-interop#325]
https://w3c-ccg.github.io/traceability-interop/openapi/#post-/presentations
and 
https://w3c-ccg.github.io/traceability-interop/openapi/#post-/presentations/submissions
should have the "TraceablePresentation" on the request schema.

**Comment by nissimsan** [comment]
https://w3c-ccg.github.io/traceability-vocab/#TraceablePresentation

**Comment by brownoxford** [comment]
Is the request here simply that we add a `workflow` property to the existing [`Presentation.yml`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/Presentation.yml) definition, or should we create a new `TraceablePresenatation.yml` that uses `allOf` to extend the existing `Presentation.yml`?

**Comment by mkhraisha** [comment]
Are there any times we are testing presentations without them being traceable presentations for interop?
If not then we should remove `Presentation.yml` and migrate it to `TraceablePresentation.yml`

**Comment by brownoxford** [comment]
Discussed on call, this is in relation to the type array.

**Comment by nissimsan** [comment]
We did this
