### ISSUE TITLE
Allow `Ed25519Signature2018` proof type in `credentials/issue` response

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#329]
If a post to `credentials/issue` specifies the `Ed25519Signature2018` for `options.type`, e.g.:

```
{
    "credential": {
        ...
    },
    "options": {
        "type": "Ed25519Signature2018"
    }
}
```

the response should be allowed to contain `Ed25519Signature2018` as `proof.type`:

```
{
    ...
    "proof": {
        "type": "Ed25519Signature2018",
        ...
    }
}
```

Currently, only one value for `type` is allowed in [LinkedDataProof.yml](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/LinkedDataProof.yml)

```
...
  type:
    type: string
    description: Linked Data Signature Suite used to produce proof.
    enum: ["JsonWebSignature2020"]
...
```

[IssueCredentialOptions.yml](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/IssueCredentialOptions.yml) however, allows several values for `type`:

```
...
  type:
    type: string
    description: Linked Data Signature Suite or signal to use JWT.
    enum: ['Ed25519Signature2018', 'JsonWebSignature2020', 'jwt_vc']
...
```

**Comment by brownoxford** [comment]
It seems that, at the very least, `LinkedDataProof.yml` should be updated to add `Ed25519Signature2018` to the `type` enum.

**Comment by nissimsan** [comment]
+1 on this. How else would we respond in those other situations.
