### ISSUE TITLE
Should we remove `options.credentialStatus` from `credentials/issue` request?

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#330]
There seems to [be some discussion](https://github.com/w3c-ccg/vc-api/issues/292#issuecomment-1162319157) in the vc-api repo regarding removing `credentialStatus` from the settable options for a credential issuer endpoint. Is this something that should be carried into the interop open api spec as well?

This relates to [IssueCredentialOptions.yml](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/IssueCredentialOptions.yml)

**Comment by BenjaminMoe** [comment]
```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/vc-revocation-list-2020/v1"
  ],
  "id": "urn:uuid:c494e8fa-fe64-448b-8075-a831713f20dd",
  "type": [
    "VerifiableCredential"
  ],
  "issuer": "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn",
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialStatus": {
    "id": "https://api.did.actor/revocation-lists/1.json#0",
    "type": "RevocationList2020Status",
    "revocationListIndex": 0,
    "revocationListCredential": "https://api.did.actor/revocation-lists/1.json"
  },
  "credentialSubject": {
    "id": "did:example:123"
  }
}
```

**Comment by brownoxford** [comment]
@BenjaminMoe suggests we wait to see what vc-api does and react, +1 from @mkhraisha
@nissimsan is leaning towards keeping as is

Leaving this one in place to give folks time to think about and comment on this.

**Comment by nissimsan** [comment]
From a usability perspective I'm sceptical about moving revocability away from options. It will require deeper involvement from the caller's side constructing the revocation list. Better to keep this declaratively and let service providers/platform deal implement these complexities under the hood.

**Comment by brownoxford** [comment]
It does not appear that this has been removed in vc-api, suggest we close for now and revisit if things change in vc-api.
