### ISSUE TITLE
Need ability to get credentials for automated testing

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-interop#34]
We will need be able to store some OAuth2 credentials for service providers to be able to retrieve a bearer token to run integration tests using the trace vocab against various VC-API providers complying with this interop profile.  

These tests will run using [newman](https://github.com/postmanlabs/newman) from gh actions

@brownoxford can you take a task of documenting the right approach so that service providers could add credentials to be used with testing, might be as simple as gh secrets, but then we will need to figure out a storage process for a list of secrets that can be matched to a list of service providers to be tested, and document a process for securely sending that info over to an editor on this project so that the keys can be added

**Comment by brownoxford** [comment]
If I understand everything correctly, we are talking about requiring providers to provide an endpoint implementing [RFC 6749 client credentials grant](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4) and to honor access tokens issued by said endpoint. Automated testing will require both the endpoint (not sensitive) and the client credentials (sensitive) for each provider.

I am inclined to agree that [GitHub Encrypted Secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets) is probably the way to go. I would like to propose the use of gpg to encrypt secrets in transit when submitting new values to editors, but am open to other suggestions.

Should I be placing the documentation for this in the top-level README.md of this repo?

**Comment by mprorock** [comment]
+1 top level `README.md` would be the right place

**Comment by nissimsan** [comment]
@brownoxford working on proof of context this week.

**Comment by OR13** [comment]
We can close this when Ci is operating in a secure setup and tests are passing.

**Comment by brownoxford** [comment]
This initial PR sets the framework for providing the necessary configuration to fetch a client credentials grant token, next steps include:
* Create CI workflow that sets `client_secret` environment variables before running postman tests
* Refactor postman tests to begin using bearer token
* Generate additional postman tests to ensure that endpoints fail if bearer token is missing/invalid

**Comment by nissimsan** [comment]
Keeping open until at least one other party beyond mesur have implemented this. 
Transmute will make an attempt on this soon.

**Comment by OR13** [comment]
We support this now.
