### ISSUE TITLE
Clean up remaining references to alsoKnownAs[0]

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#342]
Prior to the addition of the `service` with type `TraceabilityAPI` to the DID web document OpenAPI spec, we used to rely on `alsoKnownAs[0]` from did web discovery to obtain the service endpoint a traceability API implementation.

We still use `alsoKnownAs[1]` to obtain valid DIDs for issuing credentials etc., even though `alsoKnownAs[0]` is no longer required. Additionally, some of the OpenAPI specifications require that `alsoKnownAs` have a minimum of two items.

The following steps should be taken to clean up legacy references to `alsoKnownAs` that assume the first element is a URL pointing to a traceability API implementation:

- [ ] Update all DID document examples in documentation
- [ ] Update OpenAPI specifications that require `alsoKnownAs` to contain a minimum of two elements
- [ ] Update Postman tests that use `alsoKnownAs[1]` as the `issuer` in a subsequent `credentials/issue` request

**Comment by OR13** [comment]
We are primarily using this approach due to the lack of support for DID Web.

If we required DID Web, and dropped support for DID Key, we would no longer need this relationship.

Would it be better to simply migrate to using DID Web?

**Comment by brownoxford** [comment]
I'm not suggesting we drop the use of did:web resolution and `alsoKnownAs[1]` to discover did keys, just that we no longer use the element `alsoKnownAs[0]` because we started requiring a `service` element in the resolved did and using `service.serviceEndpoint` instead of `alsoKnownAs[0]`.

Am I completely off base here? I may be misunderstanding something.

**Comment by OR13** [comment]
@brownoxford I understand your suggestion, I am commenting on not "perpetuating our hacky workaround".

If did web is required (it is).

Why even include did:key at all?

If no other did methods are included, no need for alsoknownas.

My point is that we don't need to support multiple did methods, if we implement support for did web, and expose reasonable key material.

**Comment by brownoxford** [comment]
@OR13 I could get behind that, but can we walk through the flow for a second to make sure I understand everything?

suppose:
  - I want Transmute to issue a VC for me
  - I know the endpoint for Transmute's traceability interoperability implementation
  - I know Transmute's did:web DID
  - I have the necessary OAuth2 credentials

When I submit my request to Transmute's `/credentials/issue` endpoint, I will need to have set the `issuer` property in the request body to a value that Transmute is able to map to known key material. If I understand this correctly, I still need to make a request to Transmute's `/identifiers/:did` endpoint to perform DID resolution on the did:web DID.

Previously, I would have extracted the DID `alsoKnownAs[1]` and used it as the `issuer`, should I now be using the DID URL in `assertionMethod`? What if there are more than one?

**Comment by OR13** [comment]
> If I understand this correctly, I still need to make a request to Transmute's /identifiers/:did endpoint to perform DID resolution on the did:web DID.

If you know Transmute supports did:web, and you know that the did:web supports traceability api.... you can just ask for a credential issued from that did web.

If you want to discover if a given did web supports the traceability api, you can use ANY did web resolver to see if a given did:web contains the traceability service endpoint.

If you are calling an endpoint thats secured with OAuth2 client credentials you will have already needed to register your client in order to obtain an access token.

> What if there are more than one?

What if there isn't ; )

We've been hacking did:key discovery into did:web to avoid defining additional endpoints... but why do we need to support did:key if we already have to support did web?

**Comment by brownoxford** [comment]
I am in favor of this and propose that we discuss on the next call with the goal of creating a new ready-for-pr ticket with the necessary implementation details.

**Comment by nissimsan** [comment]
Big +1 on moving to did web

**Comment by BenjaminMoe** [comment]
+1 for using `did:web`

**Comment by nissimsan** [comment]
@mkhraisha, how would Mavennet feel about this?

**Comment by mkhraisha** [comment]
+1 from my end, happy to remove support for did:key and instead assume just did:web

**Comment by nissimsan** [comment]
Seems like we can mark this ready for PR, then.

**Comment by brownoxford** [comment]
Created #389 to track the progress of removing `did:key` in favor of `did:web`

This issue can be closed.

**Comment by nissimsan** [comment]
We did this
