### ISSUE TITLE
Conformance schemas should not include embedded examples

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#343]
The `update_conformance_schemas.sh` script embeds OpenAPI schemas as json in conformance test suites, but does not prune out embedded examples. These examples are not required for schema validation, and contribute bloat to the Postman suite.

Modify `update_conformance_schemas.sh` so that schema examples are excluded from the Postman conformance suite.

**Comment by OR13** [comment]
Excellent idea!

**Comment by nissimsan** [comment]
Looks very good - support from the team
