### ISSUE TITLE
Clarify /credential/status success response

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#347]
The current success response for a post to the [`/credential/status`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/resources/credential-status.yml) endpoint is `200`, but without any defined response body.

This should either be redefined as a `204 No Content` response, or a response body should be defined. This issue should be updated with the proposed fix after discussion on our weekly call, and labeled `ready-for-pr`.

**Comment by OR13** [comment]
+1 to using `204`

**Comment by nissimsan** [comment]
If we can avoid a response body, let's avoid it.
