### ISSUE TITLE
Response code for /credentials/issue with unknown issuer id

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#349]
We recently implemented a `400 Bad Request` response if a request to `/credentials/issue` contains an `issuer` for which the server does not have private key materials, but which is otherwise well formed and correct (#311).

@TallTed called out that [`400 Bad Request`](https://www.rfc-editor.org/rfc/rfc9110.html#name-400-bad-request) is probably not the right choice, _because_ the request is well formed and correct. He suggested that instead, the response should be [`501 Not Implemented`](https://www.rfc-editor.org/rfc/rfc9110.html#name-501-not-implemented) or [`422 Unprocessable Content`](https://www.rfc-editor.org/rfc/rfc9110.html#name-422-unprocessable-content).

@brownoxford suggested that we should assume the server is properly set up, and that the missing key materials do not represent server error, so the `422` response is more appropriate than any `5XX` response. Additionally, a well-designed implementation should provide further information about the error in the `details` portion of the error response to clarify any confusion for situations like this where there is not a perfect response code.

For reference the [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110.html) content for `400`, `422`, and `501` follow (emphasis mine):

> [15.5.1. ](https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.1)[400 Bad Request](https://www.rfc-editor.org/rfc/rfc9110.html#name-400-bad-request)
The 400 (Bad Request) status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

> [15.5.21. ](https://www.rfc-editor.org/rfc/rfc9110.html#section-15.5.21)[422 Unprocessable Content](https://www.rfc-editor.org/rfc/rfc9110.html#name-422-unprocessable-content)
The 422 (Unprocessable Content) status code indicates that the server understands the content type of the request content (hence a [415 (Unsupported Media Type)](https://www.rfc-editor.org/rfc/rfc9110.html#status.415) status code is inappropriate), and **the syntax of the request content is correct, but it was unable to process the contained instructions.** For example, this status code can be sent if an XML request content contains well-formed (i.e., syntactically correct), but semantically erroneous XML instructions.

> [15.6.2. ](https://www.rfc-editor.org/rfc/rfc9110.html#section-15.6.2)[501 Not Implemented](https://www.rfc-editor.org/rfc/rfc9110.html#name-501-not-implemented)
The 501 (Not Implemented) status code indicates that the server does not support the functionality required to fulfill the request. This is the appropriate response when the server does not recognize the request method and is not capable of supporting it for any resource.
>
> A 501 response is heuristically cacheable; i.e., unless otherwise indicated by the method definition or explicit cache controls (see [Section 4.2.2](https://www.rfc-editor.org/rfc/rfc9111#section-4.2.2) of [[CACHING](https://www.rfc-editor.org/rfc/rfc9110.html#CACHING)]).

**Comment by OR13** [comment]
this should be a 400... the client should know better, than to ask for a credential with an incorrect issuer.

**Comment by BenjaminMoe** [comment]
+1 for 422. We're making the assertion that the server has been configured correctly, and the client is making a request to an identifier they do not have control over.

**Comment by OR13** [comment]
I can live with `422`

**Comment by nissimsan** [comment]
+1 on `422`

**Comment by nissimsan** [comment]
Implementing this should include conformance test `credentials_issue.credential.issuer:unknown`

**Comment by nissimsan** [comment]
Still pending PR
