### ISSUE TITLE
Update encoding for auth token requests

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#350]
Right now, we are making auth token requests in Postman using JSON encoding.

RFC 6749 defines [Client Credentials Grant Access Token Request](https://www.ietf.org/rfc/rfc6749.html#section-4.4.2) as requiring `application/x-www-form-urlencoded` encoding.

Existing postman tests and documentation should be modified to use `application/x-www-form-urlencoded` request bodies when making client credentials grant token requests to an OAuth2 provider.

**Comment by brownoxford** [comment]
Note - nothing is currently "broken", as all OAuth2 provider implementations in use are accepting JSON-encoded token request bodies and responding as we expect. We should not, however, assume that all providers will do this.

**Comment by acarnagey** [comment]
Yeah I agree, in order to match RFC
E.g. In https://github.com/w3c-ccg/traceability-interop/blob/main/docs/tutorials/authentication/authentication.postman_collection.json

Instead of 
```json
{
  "method": "POST",
  "header": [],
  "body": {
    "mode": "raw",
    "raw": "{\n    \"audience\": \"{{TOKEN_AUDIENCE}}\",\n    \"client_id\": \"{{CLIENT_ID}}\",\n    \"client_secret\": \"{{CLIENT_SECRET}}\",\n    \"grant_type\": \"client_credentials\"\n}",
    "options": {
      "raw": {
        "language": "json"
      }
    }
  },
  "url": {
    "raw": "{{TOKEN_ENDPOINT}}",
    "host": [
      "{{TOKEN_ENDPOINT}}"
    ]
  }
}
```
It should be 
```json
{
  "method": "POST",
  "header": [],
  "body": {
    "mode": "urlencoded",
    "urlencoded": [
      {
        "key": "client_id",
        "value": "{{CLIENT_ID}}",
        "type": "text"
      },
      {
        "key": "client_secret",
        "value": "{{CLIENT_SECRET}}",
        "type": "text"
      },
      {
        "key": "grant_type",
        "value": "client_credentials",
        "type": "text"
      },
      {
        "key": "audience",
        "value": "{{TOKEN_AUDIENCE}}",
        "type": "text"
      }
    ]
  },
  "url": {
    "raw": "{{TOKEN_ENDPOINT}}",
    "host": [
      "{{TOKEN_ENDPOINT}}"
    ],
  }
}
```

**Comment by OR13** [comment]
Does Auth0 or Okta have a recommendation?

**Comment by brownoxford** [comment]
> Does Auth0 or Okta have a recommendation?

Both follow RFC 6749

**Comment by brownoxford** [comment]
The fix for this has been merged, this can be closed.

**Comment by brownoxford** [comment]
Closing, done.
