### ISSUE TITLE
Should options.created in `/credentials/issue` requests be tested as a date?

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#351]
Currently, [`IssueCredentialOptions.yml`](https://github.com/mesur-io/traceability-interop/blob/main/docs/openapi/schemas/IssueCredentialOptions.yml) defines `created` as a string representing "Date the proof was created".

Should we be adding negative testing that fails if this is not a valid date/time string (we do this already for `credential.issuance_date` for `/credentials/issue`)? If so, we should also modify the OpenAPI description text for this item to indicate that "This value MUST be an XML Date Time String" ([as we do for `credential.issuance_date`](https://github.com/mesur-io/traceability-interop/blob/main/docs/openapi/schemas/Credential.yml)).

**Comment by nissimsan** [comment]
Discussion on the call, whether `created` should rather be provided by the server at issuance.

**Comment by nissimsan** [comment]
Action: Double check with VC-API. If our decision, don't include this in the request options.

**Comment by nissimsan** [comment]
https://w3c-ccg.github.io/vc-api/issuer.html#tag/Credentials

**Comment by brownoxford** [comment]
The [current vc-api schema](https://github.com/w3c-ccg/vc-api/blob/main/components/IssueCredentialOptions.yml) specifies that `created` is an _optional_ element which defaults to the current system time. As such, we should remove it from our schema and disallow manual specification of the proof creation time.

**Comment by brownoxford** [comment]
@OR13 pointed out that this would prevent VC (and VP) generation from being deterministic, and at the very least, would possibly cause issues for developers and/or testers expecting this functionality to be available.

After discussing on the call, consensus was that we should allow options.created in a request body for the `/credentials/issue` endpoint, and that we should implement testing for all relevant cases as outlined in #352.

**Comment by brownoxford** [comment]
Original topic of this issue moved to #428
