### ISSUE TITLE
Add positive testing for proof created date for `/credentials/issue` request

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#352]
The `options.created` portion of a `/credentials/issue` request is an optional value indicating "Date the proof was created.". We should add positive conformance testing for the following:

- response `proof.created` should match request value if provided
- response `proof.created` should be close to "now" if request value is omitted

**Comment by brownoxford** [comment]
Related to #351

**Comment by nissimsan** [comment]
Let's cover #351 first

**Comment by brownoxford** [comment]
Since we are removing `created` from the credential issue options, we only need to add testing to ensure that the response contains a `proof.created` date that is close to "now".
