### ISSUE TITLE
Conformance testing for /credentials/status

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#359]
Conformance testing needs to be added for the `/credentials/status` endpoint. We currently have negative testing for authentication, but that is it. Additional tests need to be added for positive testing as well as for negative testing related to invalid request body content.

This is blocked by #358, which would add more definition to the request body content that will need testing.

**Comment by brownoxford** [comment]
Added ready-for-pr

**Comment by nissimsan** [comment]
Still pending PR.

**Comment by nissimsan** [comment]
Partially done. Pending positive testing to close.

**Comment by BenjaminMoe** [comment]
Partially complete. Need to add tests for positive testing.

**Comment by nissimsan** [comment]
Pending outcome of https://github.com/w3c-ccg/traceability-interop/issues/468 in order to add tests.

**Comment by OR13** [comment]
We can address this without resolving #468

**Comment by nissimsan** [comment]
Still pending. Cheering on you Chris!

**Comment by nissimsan** [comment]
@brownoxford , are you still working on this?

**Comment by nissimsan** [comment]
Ping @brownoxford

**Comment by rhofvendahl** [comment]
Still pending 2.0 upgrade

**Comment by mkhraisha** [comment]
It is outdated, we no longer need to conformance in the /credentials/status, as the new direction is to build static fixtures with one valid, one invalid VC.
