### ISSUE TITLE
Update main Readme to include Link to postman collection

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-interop#363]

**Comment by mkhraisha** [comment]
Should also be in respec

**Comment by brownoxford** [comment]
This has not been done yet.

We should probably add this to the respec as well.

**Comment by OR13** [comment]
Add some "spec text" and "friendlyness" to the respec document.

**Comment by nissimsan** [comment]
Must include links to all collections - incl Conformance.

**Comment by brownoxford** [comment]
Items related to respec changes moved to #460
