### ISSUE TITLE
Generate historical test result index

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#364]
Pull request #362 created the necessary GitHub workflow modifications to start storing historical reports in GitHub pages. The next step in the process is to create and schedule a script that will generate an HTML index into these historical reports so that they can be easily accessed.

The generated index should be sure to translate unix timestamps from archive folder names into human-readable date strings.

**Comment by nissimsan** [comment]
Discussed on the call today. Still ready for PR.

**Comment by nissimsan** [comment]
Discussed on the call today. Still ready for PR.

**Comment by BenjaminMoe** [comment]
Lower priority to conformance testing.
