### ISSUE TITLE
enlist contact from Ryder

### ISSUE THREAD

**Issue by TallTed** [w3c-ccg/traceability-interop#368]
Recent commercials for https://ryder.com/everbetter suggest that they ("300+ supply chain engineers") may have already done a lot of the work we're doing, in both traceability-interop and traceability-vocab.  I'm posting this in the former, but it could reasonably be considered to live in either, or perhaps an overarching repo/work-item.

If anyone has a contact within Ryder (I do not), trying to enlist their team in CCG, W3C, etc., seems likely to be a worthwhile exercise!

**Comment by nissimsan** [comment]
Does anyone have contacts at Ryder?
