### ISSUE TITLE
Change and document procedure for distributing meeting agenda

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#371]
Right now, the procedure for running weekly meetings includes instructions to post a meeting agenda link into the chat so that it can be parsed into the meeting minutes output HTML. We are currently posting a link to a static, standing agenda, but as @TallTed pointed out, a better process would be to send the agenda to the mailing list before each meeting and to link to that archived email.

For example, see the meeting minutes for a recent vc-api group:

https://w3c-ccg.github.io/meetings/2022-08-16-vcapi/

**Comment by nissimsan** [comment]
Update documentation. Still pending PR.

**Comment by BenjaminMoe** [comment]
Reminder to modify the meeting agenda. Publish to mailing list.
