### ISSUE TITLE
Conformance test suite should support multi-tenant and dedicated tenant setups

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-interop#377]
On a multi-tenant platform, `{{API_BASE_URL}}/did.json` does not work because the DID document sits under a tenant path. The conformance test suite must also support this. 

Possible solutions could be: 
1. Deducting the tenant path from `ORGANIZATION_DID_WEB`
2. Adding a tenant path as dedicated environment variable (github secret)

**Comment by OR13** [comment]
This is related to the conversation we had regarding "how to discover the issuer"... TLDR... use did:web... but that means you need to implement support for did:web, using either:

1. `.well-known`... which limits you to "single tenant use cases".
2. `path based routes`... which work for both.

We currently only support 2, I think 1 should be avoided personally... since there are lots of cases where you might want the same origin to host multiple issuer dids... ( company divisions, inventory, locations, etc...)

**Comment by nissimsan** [comment]
@brownoxford, FYI - let's continue solutioning here.

**Comment by nissimsan** [comment]
Noting that this affects not only the `did_json` test, but all the ones depending on `getIssuerId`: 
https://github.com/w3c-ccg/traceability-interop/blob/main/tests/conformance_suite.postman_collection.json#L4369

**Comment by BenjaminMoe** [comment]
`https://platform.transmute.industries/credentials/issue` is a site-wide resource

`https://platform.transmute.industries/organizations/org_mt46IVhChCDYEV6o/did.json` is a unique resource for an identifier

`https://platform.transmute.industries/organizations/org_mt46IVhChCDYEV6o/presentations/available` is an end point for a specific tenant

**Comment by nissimsan** [comment]
Next step on this is a PR on the respec describing this

**Comment by nissimsan** [comment]
@brownoxford, please note https://github.com/w3c-ccg/traceability-interop/pull/410 which addresses part of this issue. Specifically it fixes the `GET did_JSON` test case (1st in the conformance collection). 

I hope this helps clarify the issue?

We need to do the same for `credential_issuer_id` (and later also presentation endpoint). Here though, I think we should rather base is on an authenticated `/resolve`-call. This we can do either in the top level pre-request script, or with a couple of normal Postman calls. I would prefer the latter, but expect you probably don't, so want to hear your thoughts first before progressing further.

**Comment by nissimsan** [comment]
We've addressed a lot of this.
