### ISSUE TITLE
pre vcapi: credentialStatus should be an object, not an array 

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#379]
https://github.com/w3c-ccg/traceability-interop/blob/a00d12c20075395764ae2d587f8c9c0ccd563060/docs/openapi/resources/credential-status.yml#L24

https://github.com/w3c-ccg/vc-api/blob/main/components/IssueCredentialOptions.yml#L30

https://github.com/w3c-ccg/vc-api/issues/225#issuecomment-1238641689

**Comment by OR13** [comment]
This would be a breaking change for implementations... cc @brownoxford

**Comment by brownoxford** [comment]
For reference, recent PR #366 modified the trace interop OpenAPI definition for the request body of a `/credential/status` request in response to issue #358.

I believe that the `vc-api` component you have linked to is used in the body of a `/credentials/issue` endpoint.

@OR13 is there still an issue here?

**Comment by OR13** [comment]
hmm now I am not sure...

I think we expect the data shape of both to be similar.

**Comment by brownoxford** [comment]
We are in alignment with vc-api here (array of objects) when [updating a credential](https://w3c-ccg.github.io/vc-api/#update-status)
