### ISSUE TITLE
Selective Disclosure credentials

### ISSUE THREAD

**Issue by brianorwhatever** [w3c-ccg/traceability-interop#39]
Follow on from #20. This interoperability profile should include the ability to selectively disclose attributes of credentials. This is currently blocked because of a bug in the BBS+ LD signature suite. https://github.com/w3c-ccg/ldp-bbs2020/issues/62

We will continue to monitor the situation and include them here once possible.

**Comment by brianorwhatever** [comment]
Can someone with permissions please assign me and add a blocker label?

**Comment by nissimsan** [comment]
@brianorwhatever , any updates on this?

**Comment by OR13** [comment]
Potential alternatives:

- https://w3c-ccg.github.io/Merkle-Disclosure-2021/
- https://w3c-ccg.github.io/Merkle-Disclosure-2021/jwp/

None of these approaches to SD are great right now.

**Comment by mprorock** [comment]
happy to add a section to spec on this - will self assign unless @brianorwhatever jumps back in

**Comment by brianorwhatever** [comment]
Great, feel free @mprorock. Was on bbs+ call yesterday and the timeline was not very solid. I don't think they are prioritizing fixing the old suite vs focusing on the new version that will be brought to IETF

**Comment by mprorock** [comment]
addressed in PR #48

**Comment by OR13** [comment]
There is still nothing to use, but we leave this open until that changes.

**Comment by OR13** [comment]
There is still nothing to do here.

**Comment by OR13** [comment]
There is still nothing to do here.

**Comment by OR13** [comment]
There is still nothing to do here.

**Comment by OR13** [comment]
There is still nothing to do here.

**Comment by OR13** [comment]
There is still nothing to do here.

**Comment by mkhraisha** [comment]
There is still nothing to do here.

**Comment by brownoxford** [comment]
There is still nothing to do here.

**Comment by BenjaminMoe** [comment]
Can't build an end point until foundation is in flux. Ask Brian to update.

**Comment by nissimsan** [comment]
@brianorwhatever, we just discussed this again on our weekly call. Curious if you might have any updates you can share on the topic?

**Comment by brianorwhatever** [comment]
I know the BBS+ group at DIF presented to IETF this week with positive reception. Hopefully the work will be brought over to IETF soon and there will be something to do here then

**Comment by nissimsan** [comment]
Still externally blocked.

**Comment by brownoxford** [comment]
Still blocked

**Comment by OR13** [comment]
still blocked, suggest closing... we are following the thread in CFRG.
