### ISSUE TITLE
Fix `credentialSubject` format in `/credentials/verify`

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#397]
The base VC used for requests in the "Credentials - Verify" folder of the conformance testing still uses a string for `credentialSubject` instead of the new object-with-optional-id format required after fixing issue #372.

Update the test suite to use an appropriate value for `credentialSubject`

**Comment by brownoxford** [comment]
We did this with PR #400, this can be closed

**Comment by nissimsan** [comment]
We did this.
