### ISSUE TITLE
authentication of the presentation section is confusing

### ISSUE THREAD

**Issue by Sakurann** [w3c-ccg/traceability-interop#401]
Below language was confusing..

> This API specification describes two ways in which presentations from a holder to a verifier can be authenticated:
> - DIDAuth, authenticated by proving a Verifiable Presentation signed over a challenge.

DIDAuth should be defined.. signing over a challenge is pretty protocol specific.. how do you get the challenge, etc.

> - OAuth, authenticated with an access token provided in the request header (with scope of submit:presentations). To avoid double authentication, a Presentation object — not a Verifiable Presentation, i.e., lacking a VP proof element — is passed in the request body.

Access Tokens are not meant to be used for authentication.. Access Tokens are opaque to the client, client does not sign Access Tokens, unlike Client's ability to generate Verifiable Presentations. Access Token is used to access a resource based on the permissions defined by the scopes.

**Comment by brownoxford** [comment]
@OR13 would now be a good time to start removing DIDAuth from the spec?

@Sakurann I agree with you regarding the intended use of an OAuth access token, and believe this section would be better written as "OAuth, authorized with an access token...". Would you suggest additional changes?

**Comment by OR13** [comment]
IMO, we should not remove `DIDAuth` from the spec, because we don't yet have a standard alternative to it.

I am in favor of refining the language around `OAuth secured` presentations in a M2M context.

**Comment by nissimsan** [comment]
A PR updating the language about the both types of presentations needed here, pls.

**Comment by OR13** [comment]
Make it clear when "holder" / "subject" binding happens (with DIDAuth + VP Request Spec) and when it doesn't ( OAuth Presentations).

**Comment by Sakurann** [comment]
what is a 'VP Request Spec' and 'OAuth Presentations'? presentation protocol and holder binding are orthogonal since holder binding happens at the credential level.

**Comment by Sakurann** [comment]
SIOPv2 is DIDAuth

**Comment by msporny** [comment]
DID Authentication is covered here, FWIW: https://w3c-ccg.github.io/vp-request-spec/#did-authentication

**Comment by BenjaminMoe** [comment]
Proposal: Add clarification around OAuth and DID Auth in the respec document

**Comment by nissimsan** [comment]
This section certainly needed some love. Updated [here](https://github.com/w3c-ccg/traceability-interop/pull/451), pls let me know if you think it can be further improved. 
Thanks for the feedback and links.

**Comment by nissimsan** [comment]
@Sakurann, closing this. Please let me know if you have suggestions on how this can be further improved: https://w3c-ccg.github.io/traceability-interop/draft/#presentation-authentication
