### ISSUE TITLE
.NET EPCIS Postman Example

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#402]
https://github.com/FasTnT/epcis/blob/develop/documents/EPCIS%20Examples%20-%201.2.postman_collection.json

For reference... wondering if we would expose direct or wrapped interfaces for this in the future.

**Comment by nissimsan** [comment]
I'll need to pick this up sometime soon.

**Comment by brownoxford** [comment]
Discussed on call - closing, nobody intends to implement.

**Comment by OR13** [comment]
I suggest we close, there is no plan to implement this.
