### ISSUE TITLE
Differentiate credentials/verify 400 errors

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#406]
Currently, the `/credentials/verify` endpoint returns a 400 error for bad requests. This should be made more specific so that there are two types of defined bad requests (both with 400 codes).

One type should indicate that the presented verifiable credential does not conform to the schema, and the second type should indicate that the provided proof signature is invalid.

**Comment by BenjaminMoe** [comment]
There is the case of no proof being provided.

**Comment by brownoxford** [comment]
> There is also the case of no proof being provided.

The `proof` property is a required element of the [verifiable credential schema](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/VerifiableCredential.yml), so I think that would fall under the first variation of 400 error (not conforming to schema).

**Comment by brownoxford** [comment]
This should be closed in favor of #431

**Comment by nissimsan** [comment]
Closing this.
