### ISSUE TITLE
Deprecate did:key in favor of did:jwk

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#427]
Today we use `did:key` because its easy to test with.

In the future, we might use `did:jwk` instead.

several reasons why `did:jwk` would be better than `did:key`.

https://lists.w3.org/Archives/Public/public-credentials/2022Sep/0029.html

https://github.com/decentralized-identity/universal-resolver/pull/318

[https://dev.uniresolver.io/1.0/identifiers/did:jwk:eyJraWQiOiJ1cm4...](https://dev.uniresolver.io/1.0/identifiers/did%3Ajwk%3AeyJraWQiOiJ1cm46aWV0ZjpwYXJhbXM6b2F1dGg6andrLXRodW1icHJpbnQ6c2hhLTI1NjpGZk1iek9qTW1RNGVmVDZrdndUSUpqZWxUcWpsMHhqRUlXUTJxb2JzUk1NIiwia3R5IjoiT0tQIiwiY3J2IjoiRWQyNTUxOSIsImFsZyI6IkVkRFNBIiwieCI6IkFOUmpIX3p4Y0tCeHNqUlBVdHpSYnA3RlNWTEtKWFE5QVBYOU1QMWo3azQifQ)

**Comment by BenjaminMoe** [comment]
1. Only support `did:web` and `did:key`?
2. Only support `did:web`?
3. Only support `did:web`, `did:key`, `did:jwk`?

**Comment by OR13** [comment]
or `did:web` and `did:jwk`.

**Comment by BenjaminMoe** [comment]
Have it clear what methods are required.

**Comment by OR13** [comment]
PROPOSAL: `did:web` is required, not other methods are supported by the profile moving forward.

**Comment by nissimsan** [comment]
> Today we use did:key because its easy to test with. 
I don't believe we do on trace-interop. 

We are only using `did:web` on trace-interop. I assert that mainly fomalizing what we do already. 

Let's make `did:jwk` depend on what requirements emerge from DHS.

**Comment by brownoxford** [comment]
Discussed on call - only did:web is required to support the profile, did:key and did:jwk are not under test.
