### ISSUE TITLE
Add `/credentials/verify` failed verification testing

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#431]
Additional tests should be added to the `/credentials/verify` conformance suite to ensure that the response received is correct when a credential is well-formed but otherwise invalid, e.g., because of a bad signature.

**Comment by nissimsan** [comment]
Placeholder issue

**Comment by brownoxford** [comment]
Intention is to test that response is 200 with verified = false in the body.

**Comment by BenjaminMoe** [comment]
@brownoxford was out. Will will up.
