### ISSUE TITLE
Open Wallet Foundation

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#438]
How is our work related to "Cloud Wallets"?

Is there an opportunity to collaborate with OWF?

**Comment by BenjaminMoe** [comment]
Reviewed on call. Need more information from @OR13 .

**Comment by BenjaminMoe** [comment]
Note: We should ask @OR13 to comment on the first half of the call to make it a special agenda item.

**Comment by OR13** [comment]
We've heard that the OWF will accept code related to DIDs and VCs, and we believe api.did.actor which implements our tests here, might be accepted... Once we know for sure we will start that process.

**Comment by brownoxford** [comment]
Discussed on call, @OR13 are there any updates here?
