### ISSUE TITLE
Document manual scribing procedures

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#439]
On the 2022-10-11 call we voted to scribe manually instead of relying on the AI scribe. The procedures for running meetings need to be updated to include documentation on manual scribing.

**Comment by BenjaminMoe** [comment]
Proposal: Update readme to reflect manual scribe procedure: https://github.com/w3c-ccg/traceability-interop#hosting-instructions

**Comment by nissimsan** [comment]
https://www.w3.org/2008/04/scribe.html

**Comment by BenjaminMoe** [comment]
Needs documentation update.
