### ISSUE TITLE
Credential string conformance<>interop conflict

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-interop#447]
The `credentials_verify:vc:string` conformance test conflicts with [VC JWT interop test](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/tutorials/vc-jwt/vc-jwt.collection.json), which takes a string credential subject.

**Comment by brownoxford** [comment]
discussed on call - we are leaving the test as is because it currently presents an invalid string for JWT and should still throw an error.

for further discussion: how should we handle this going forward?

**Comment by OR13** [comment]
don't use the header... thats just a hack I made to start the conversation. sync with the vc api folks on how they plan to support JWT... @mkhraisha @mprorock are you aware of how VC API handles these scenarios today?

**Comment by BenjaminMoe** [comment]
Check string value for valid JWT or not.

**Comment by BenjaminMoe** [comment]
Follow up would be to add positive tests.

**Comment by brownoxford** [comment]
Suggest we close in favor of #453
