### ISSUE TITLE
Allow JWT in `credentials/verify`

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#453]
Account for the possibility that the request body for a `/credentials/verify` request will represent a JWT. Right now, `verifiableCredential` cannot be a string, but we may want to allow that and then have implementations check to see whether the string is a valid JWT. Alternatively, we could include an object property of `jwt` and put the JWT there.

See https://github.com/w3c-ccg/traceability-interop/issues/447 for some additional context

**Comment by brownoxford** [comment]
Discussed on call, no work has been done here.

**Comment by nissimsan** [comment]
In the near future we need to support application/json+jwt.
Adding different content types as supporting args, in general. If I were to tackle, would start by updating all schema defs to be oneOf, then concrete schemas for those types.

**Comment by OR13** [comment]
its `application/vc+ld+jwt` `application/vp+ld+jwt`

`application/vc+ld+json` `application/vp+ld+json`

**Comment by OR13** [comment]
start by adding concrete schemas for each supported type, then update APIs to use oneOf supported types.

**Comment by brownoxford** [comment]
Discussed on call and one option is dedicating the entire post body to the encoded credential, and using content-type to switch. Another option is keeping the nesting and using something like query string parameters to switch. Preference is for the former.

**Comment by OR13** [comment]
Please comment on https://github.com/w3c/vc-jose-cose/issues/141

**Comment by rhofvendahl** [comment]
Chris working on it

**Comment by mkhraisha** [comment]
We no longer support `credential/verify` as we now only care about cross-trust boundary communication.
