### ISSUE TITLE
Remove `options.type` from `/credentials/issue` request

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#454]
Trace interop made the `options.type` property in [`IssueCredentialOptions`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/IssueCredentialOptions.yml) required on 2022-05-13 with [PR #228](https://github.com/w3c-ccg/traceability-interop/pull/228).

This is actually problematic because vc-api vc-api removed `options.type` property from `IssueCredentialOptions` on 2022-03-15 in [commit 8a419de](https://github.com/w3c-ccg/vc-api/commit/8a419de0092c601dec566c28cad7edb1b51a922a), _and_ [`IssueCredentialOptions`](https://github.com/w3c-ccg/vc-api/blob/main/components/IssueCredentialOptions.yml) includes the `additionalProperties: false` property.

This combination makes the trace-interop schema incompatible with the vc-api schema.

There is an [issue in vc-api](https://github.com/w3c-ccg/vc-api/issues/292) that discusses having sane defaults that are internally consistent. In this case, multiple endpoints would be needed in order to provide different signature types. Note that this issue also suggests that specifying `credentialStatus` during a call to `/credentials/issue` may become an anti-pattern in time.

The vc-api-test-suite-implementations repo [has opened an issue](https://github.com/w3c-ccg/vc-api-test-suite-implementations/issues/55) regarding this problem during testing.

**Note:** vc-api still allows `options.type` in a `/presentations/prove` request with the following description (which is the same description that was previously used for `options.type` in `/credentials/issue`):
> The type of the proof. Default is an appropriate proof type corresponding to the verification method. 

---

**Proposal:** Follow the vc-api lead to remove `options.type` from `IssueCredentialsOptions.yml` and require implementations to select and use "an appropriate proof type corresponding to the verification method" when issuing verifiable credentials.

**Comment by OR13** [comment]
This will destroy the ability to request a proof format, I suggest we adopt vc-jwt as the proof format at the same time we do this, because if we don't we won't be able to test that after this change.

**Comment by OR13** [comment]
My guess is that this will cause a lot of problems, and is perhaps not a good idea, despite being adopted by the vc-api.

**Comment by TallTed** [comment]
`X-` header naming is strongly discouraged. `VC-PROOF-TYPE` seems a viable option.

**Comment by brownoxford** [comment]
Discussed on call today - we want to leave this in as a required item.
