### ISSUE TITLE
Admin access for adding oauth secret

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-interop#46]
@brownoxford and @OR13, could you (temporarily) grant me admin privileges, so I can try adding the oauth secret. 

https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository

**Comment by brownoxford** [comment]
@nissimsan I don't have the ability to modify privs, @OR13 can you help on this one?

We still need a [maintainer volunteer](https://github.com/w3c-ccg/traceability-interop/tree/main/tests/postman#providing-secrets) to accept gpg encrypted values for oauth secrets.

**Comment by OR13** [comment]
I gave access, but we still need to confirm the access and instructions are sufficient to resolve.
