### ISSUE TITLE
Update respec with links to postman collection

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#460]
Issue #363 was created to update the documentation related to importing postman collections, and there were several requests to add similar text to the respec document. This issue has been created to track those additional requests so that the original issue can be closed.

@mkhraisha, @OR13 can you please provide more details/direction on how this should be represented in the respec?

**Comment by brownoxford** [comment]
Discussed on call - I will take a stab at this and we can discuss in PR

**Comment by nissimsan** [comment]
@brownoxford , any updates on this?

**Comment by nissimsan** [comment]
@brownoxford , any updates on this?

**Comment by nissimsan** [comment]
Ping @brownoxford

**Comment by rhofvendahl** [comment]
@brownoxford WIP
