### ISSUE TITLE
Workflows section should be more generic

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-interop#464]
I'm getting feedback that the section on Workflows is overly American: 

https://w3c-ccg.github.io/traceability-interop/draft/#workflows

While it's just a non-normative example, I do agree that it could be made more generic. For example, just say "Customs" instead of CBP.

**Comment by TallTed** [comment]
Note that "Customs" is not universal, either.

Whatever more-generic term/label is chosen (which might yet be "Customs"), it would probably be good to include some specific examples (such as United States Customs and Border Protection, Canada Border Services Agency, Mexican National Customs Agency (ANAM), etc.)

**Comment by nissimsan** [comment]
Let's add diverse flare on this, not removing what we have.

**Comment by nissimsan** [comment]
I'll look for more international use cases. Ask Steve for requirements.

**Comment by nissimsan** [comment]
We did this
