### ISSUE TITLE
Require `verifications` array in verification response

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#469]
Action item from 2022-11-15 weekly meeting.

@OR13 suggested that simply including `verified` property in verification result is not very helpful in the case that verification failed.

> ... at the library implementation layer, often you will see an implementation provide details around why a verification failed. It could be because date was out of range, or because revocation was not resolvable, or credential was revoked. This is information that we could be providing, as a nice to have enhancement

@nissimsan pointed out that we do have some of this already in the form of the optional `verifications` property.

@brownoxford confirmed that the [current verification response](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/VerificationResult.yml) from verification of credentials and presentations only requires the `verified` boolean property to be present.

*Proposal:* make `verifications` array required in verification response.

**Comment by brownoxford** [comment]
Right now, the [Verification](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/Verification.yml) schema defines an object with `title`, `status`, and `description`. The first two are required and are enums with defined possible values, `description` is optional.

Do we want to mandate iteration over all the verifications that passed? That seems like overkill and only useful if a client wants to validate that certain verifications have been performed. It seems much more useful for the `verifications` array to be required only in the case where `verified` is false so that the client has an idea of where to start troubleshooting. This type of conditional requirement is not possible to express in OpenAPI 3.0, so it would have to be added as a descriptive comment (we can, of course, still test this in Postman).

**Comment by brownoxford** [comment]
@nissimsan Your example in the previous comment includes several additional items (`checks`, `warnings`, `errors`), which seems like quite a lot of info. I think that in order to move this to `ready-for-pr`, we need to have some concrete proposals regarding what additional elements need to be present in both the positive and negative responses. We should take care to ensure that the schema we define is easily testable.

It would also be helpful to have some example use cases where positive verification details would be helpful to complement the negative use case (knowing what failed and why helps to fix errors).

**Comment by nissimsan** [comment]
Discussion on the call: 

1. Choice whether to include `verifications` also when passing - or only when failing?

**Comment by paulfdietrich** [comment]
As an anecdote, we were providing a library for verification with a single verify endpoint.  The customer specifically asked for a black box where they would get a success/Fail output.  Upon delivery, the first thing they asked for is a verification result with the list of steps that were executed as part of the verification process.  In our case, this included credential verification as well as business rule verifications that were necessary to validate the presentation.  

From this experience I believe it may be valuable to offer the verifyResults array regardless of whether each individual tests passed or failed.  

I don't have a strong opinion on how to enumerate or model these results.  Here is an example of what we did 

              "verificationStatus": [
                {
                  "code": "10000200",
                  "rule": "Credential proof verification.",
                  "credentail": "GS1PrefixLicenceCredential",
                  "subjectField": "proof",
                  "value": "",
                  "status": "Passed"
                },
                {
                  "code": "10000500",
                  "rule": "Credential has been revoked.",
                  "credentail": "GS1PrefixLicenceCredential",
                  "subjectField": "revocation",
                  "value": "",
                  "status": "Passed"
                }

**Comment by brownoxford** [comment]
@nissimsan, can you comment on what each of these potential verification steps is doing specifically?

- Proof
- Activation
- Expired
- Revocation
- Signature
