### ISSUE TITLE
Enable branch protection

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#472]
We have been manually requiring two PR reviews before merging, should we enforce this by enabling branch protection and configuring the number of required reviews?

**Comment by nissimsan** [comment]
Absolutely!!

**Comment by brownoxford** [comment]
I will look into seeing whether we can get around CI commits having issues here as @BenjaminMoe reported.

**Comment by brownoxford** [comment]
Branch protection has been enabled for the `main` branch.
* Users can no longer force-push to the `main` branch.
* The `main` branch cannot be deleted.
* Pull requests are required before merging.
* Two approvals are required in order to merge a Pull Request.

@BenjaminMoe, as it happens, our CI makes changes on push to any branch, and branch protection now prevents pushing directly to `main`. In theory, CI should never actually need to make changes to the `main` branch (they will be made on the PR branches), so I don't think that there will be problems here like there are in the trace-vocab repository. I will monitor for problems and try to address them if they come up.
