### ISSUE TITLE
Add tests for required `@context` entry

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#474]
Trace vocab [ReSpec document contains the following normative statements](https://w3c-ccg.github.io/traceability-vocab/#extensions-to-standard) regarding `@context` in verifiable credentials and presentations:

> The `@context` MUST contain "https://w3id.org/traceability/v1".

The current Postman conformance suite does not contain tests verifying this requirement, and needs to be updated.

**Comment by TallTed** [comment]
@brownoxford — Gotta code fence that `@context` in the quote...

**Comment by brownoxford** [comment]
> @brownoxford — Gotta code fence that `@context` in the quote...

sigh. I thought I got them all :(
