### ISSUE TITLE
Examples which contain proofs must be re-signed

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#479]
There are a number of examples in the OpenAPI specification of verifiable credentials and presentations which have had content modified, e.g., for #473 and #474), but which have not been regenerated to have correct signatures. These should be updated so that they are actual, valid, examples.

The following OpenAPI spec files contain examples with signatures:

- [ ] [`LinkedDataProof.yml`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/LinkedDataProof.yml)
- [ ] [`Presentation.yml`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/Presentation.yml)
- [ ] [`RevocationListCredential.yml`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/RevocationListCredential.yml)
- [ ] [`SerializedVerifiableCredential.yml`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/SerializedVerifiableCredential.yml)
- [ ] [`SerializedVerifiablePresentation.yml`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/SerializedVerifiablePresentation.yml)
- [ ] [`TraceablePresentation.yml`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/TraceablePresentation.yml)
- [ ] [`VerifiableCredential`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/VerifiableCredential.yml)
- [ ] [`VerifiablePresentation`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/VerifiablePresentation.yml)

**Comment by nissimsan** [comment]
Solve this by including support for JWT too.

**Comment by OR13** [comment]
This would apply to all credential examples which include proofs, and we probably want to refer to trace vocab examples: https://www.w3.org/TR/vc-data-model/#example-usage-of-the-id-property

**Comment by brownoxford** [comment]
Updated initial comment to include a checklist of `yml` files that need updated examples.

@OR13 - I agree that we should have multiple proof types in examples like vc-data-model is doing, but believe the addition of that should be a separate issue.

**Comment by nissimsan** [comment]
Discussed on call. Looking for volunteers.

**Comment by OR13** [comment]
We should do this soon, it partially blocks starting the rest of the v2 changes.

**Comment by nissimsan** [comment]
Keep proof property, but don't add constraints around it.

**Comment by nissimsan** [comment]
Closing without fixing.
