### ISSUE TITLE
Document and clarify verification result tests

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#481]
The [`VerificationResult`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/VerificationResult.yml) schema defines a number of tests that can be represented (via the `title` enum) in a verification response:

- Proof
- Activation
- Expired
- Revocation
- Signature

Each of these should be documented in the OpenAPI spec so that it is clear what specific test is being Passed or Failed. Additionally, any changes to the wording or content of this enum should be discussed here and implemented as part of the PR.

**Comment by TallTed** [comment]
As I just commented somewhere nearby... These test labels should agree with each other. There may be another column, or some changes to some of these cells, to also consider.

| a | b |
|---|---|
| Proved | Proof |
| Activated | Activation |
| Expired | Expiration |
| Revoked | Revocation |
| Signed | Signature |

**Comment by nissimsan** [comment]
The five enum values look good to me. 

I also vote on sticking with the familiar column `b`.

**Comment by brownoxford** [comment]
Before we make this ready-for-pr, I'd like to come to a consensus on what each of these checks is doing so that it can be documented. I'm unsure about the `Proof` vs. `Signature`, for example.

More specifically, it would be good to have a one-line description of each check, as well as a list of conditions that would result in a check failure.

**Comment by brownoxford** [comment]
Discussed on call
- Only the `verified` boolean is required
- Additional properties: true

**Comment by rhofvendahl** [comment]
@brownoxford Could you add me to the mesur interop repo so I can submit a PR with the minor VerificationResult updates?

& regarding the documentation, I'm also unclear on some of these tests. Is this something to bring up on the next interop call, or is there another path to resolution?

**Comment by brownoxford** [comment]
@rhofvendahl I've sent you an invite to the mesur.io repo.

Essentially what we have agreed to do here is modify [`VerificationResult.yml`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/VerificationResult.yml) to remove all reference to the `verifications` property and instead replace it with [`additionalProperties: true`](https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties) to allow implementations to return any additional property items that they would like.

**Comment by rhofvendahl** [comment]
Addressed this (hopefully) in a PR.
