### ISSUE TITLE
Should we update the spec to use Status List 2021?

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#482]
Right now the [spec indicates that](https://w3c-ccg.github.io/traceability-interop/draft/#linked-data-signature-suites):

> Any system conforming with this specification for interoperability MUST support[ Revocation List 2020 ](https://w3c-ccg.github.io/vc-status-rl-2020/)to handle revocation of Verifiable credentials.

Is it time to change this to [Status List 2021](https://w3c-ccg.github.io/vc-status-list-2021/)?

This change was suggested by @mprorock, and I'd like to hear thoughts from @OR13 and @mkhraisha as draft editors.

**Comment by mkhraisha** [comment]
I believe it is.

**Comment by nissimsan** [comment]
Suggestion to let 2021 mature a bit further before taking this on.

**Comment by OR13** [comment]
Assigned one of the editors of the work item: https://w3c.github.io/vc-status-list-2021/

**Comment by nissimsan** [comment]
Let's do this together with VC2.0 upgrade.

**Comment by rhofvendahl** [comment]
Let's do this together with VC2.0 upgrade.

**Comment by PatStLouis** [comment]
Ignore my comment, I had the wrong link, correct link is [https://w3id.org/vc/status-list/2021/v1](https://w3id.org/vc/status-list/2021/v1) 

However the use of BitstringStatusList instead of the StatusList2021 sounds like it would be preferable with the VC2.0 upgrade?

**Comment by mkhraisha** [comment]
Will tackle this soon, to change StatusList2021 to BitstringStatus list

**Comment by mkhraisha** [comment]
This is complete
