### ISSUE TITLE
Question about Credentials Verify Tutorial Postman Collection Flow

### ISSUE THREAD

**Issue by tsnyder-gs1us** [w3c-ccg/traceability-interop#488]
Trying to get a better understanding how the the postman variable flow works in the Credentials Verify Tutorial Postman Collection. 

According to the openapi definition for [/credentials/issue](https://w3c-ccg.github.io/traceability-interop/openapi/#post-/credentials/issue) the expected output should be return as `{ verifiableCredential: { ... } }`. In the postman collection tests I see the result is stored in a variable called `verifiable_credential`.

```javascript
// Verifiable credential must be made available to later requests
pm.test("`verifiable_credential` persisted to collectionVariables", function() {
    const verifiable_credential = JSON.stringify(pm.response.json());
    pm.collectionVariables.set("verifiable_credential", verifiable_credential);
})
```

Then in the `/credentials/verify` method the variable is passed to the verifier end point (see below postman code). The issue I running into is when the verifier is called I get a parameter that is `{ verifiableCredential:  verifiableCredential: { ... }  }`

Postman code:
```javascript
{
    "verifiableCredential": {{verifiable_credential}}
}
```

Is this the expected behavior or is there a postman setting so the variable is correctly mapped to the HTTP body?

**Comment by BenjaminMoe** [comment]
The response object for `/credentials/issue` is not consistent, which one of these is correct?

1. The [CredentialVerifyColection](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/tutorials/credentials-verify/credentials-verify.postman_collection.json) has the response to `/credentials/issue` as the verifiable credential directly
2. The [/credentials/issue](https://w3c-ccg.github.io/traceability-interop/openapi/#post-/credentials/issue) documentation specifies the response for `/credentials/issue` as being wrapped in `verifiableCredential`
3. The [ConformanceSuite](https://github.com/w3c-ccg/traceability-interop/blob/main/tests/conformance_suite.postman_collection.json) specifies the response for `/credentials/issue` as being wrapped in `verifiableCredential`

The OpenAPI documentation and Conformance Suite are correct. The tutorial is outdated.

**Comment by BenjaminMoe** [comment]
@brownoxford @nissimsan I think our tutorials and interop tests are using one response, and the documentation and conformance using another response.

**Comment by OR13** [comment]
https://w3c-ccg.github.io/vc-api/#issue-credential

The spec says `verifiableCredential` is in the response for issue.

Our OAS files should be updated.

**Comment by mprorock** [comment]
@brownoxford - eyse on please, but i think as @OR13 mentioned above the OAS files need an update

**Comment by brownoxford** [comment]
> Our OAS files should be updated.

[OAS is fine](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/resources/credential-issuer.yml#L25-L36), see below (let me know if I'm missing something here).

This a bug in the interop test suite introduced by #455 (and maybe more from #456), and can be fixed by storing only the nested credential so that code written before #455 was fixed continues to work properly:

```javascript
// Verifiable credential must be made available to later requests
pm.test("`verifiable_credential` persisted to collectionVariables", function() {
    const {verifiableCredential} = pm.response.json();
    pm.collectionVariables.set("verifiable_credential", JSON.stringify(verifiableCredential));
})
```

**Comment by OR13** [comment]
I stand corrected, I believe.

**Comment by BenjaminMoe** [comment]
Agreed, ready for PR.

**Comment by brownoxford** [comment]
This was done - unless anyone objects, we should close next time it comes up.

**Comment by nissimsan** [comment]
This is done.
