### ISSUE TITLE
Add clarity on Workflow ID and credentials expected

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-interop#490]
need to add clarity about how and where workflows may be retrieved from, and examples of workflow definition contents

**Comment by nissimsan** [comment]
Make a generic test suite with TraceablePres with an IntentToImport credential.

**Comment by mkhraisha** [comment]
Two separate https://github.com/w3c-ccg/traceability-interop/pull/487#discussion_r1087967307 action items:

Text to explain and Test suite to test for it.

**Comment by mkhraisha** [comment]
@mprorock  to provide text, 
@nissimsan to provide test updates.
