### ISSUE TITLE
Spec should describe weighted average calculation

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#494]
Section 7.1 of the spec contains the following paragraph:

>Following the credential "type", a space followed by a numeric value that ranges from 0 to 1, MAY be added. If this value is not provided a value of 1 MUST by inferred by any system using this property. This numeric value MUST be referred to as "weight", and MAY be utilized to calculate a weighted average indicating the completeness of a particular workflow instance.

The standard calculation for weighted averages and algorithm for calculating this weighted average indicating the completeness of available information <em>SHOULD</em> be described, along with examples.

**Comment by brownoxford** [comment]
Be sure to include an example

**Comment by nissimsan** [comment]
I suggest we remove this paragraph.

**Comment by nissimsan** [comment]
Described in https://github.com/w3c-ccg/traceability-interop/pull/557 - we can close this.
