### ISSUE TITLE
Workflow manifest document is referenced, but not defined

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#495]
Section 7.1 of the spec contains the following text:

> A workflow definition indended for use with US CBP imports MUST have a corresponding plain text workflow manifest document that may be uniquely identified, referenced, and retrieved by a third party in a publicly accessible and documented manner by the UUID of the workflow definition.
>
> This workflow manifest document MUST list each required credential from the[ Traceability Vocabulary](https://w3c-ccg.github.io/traceability-vocab/#terminology), one per line, and identified by the "type" of credential, for the workflow to be considered "complete". Completeness in this sense refers to an optimal state where all possible information that can be provided in relation to that workflow definition is present.

There should be more definition regarding the new "workflow manifest document" referenced in these paragraphs.

**Comment by nissimsan** [comment]
It sounds like this needs updating rather than deletion.
