### ISSUE TITLE
Clarify best practices for retrieval and ownership of data

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#496]
Section 8.1.1 of the spec includes the following paragraph:

> To assemble a collection of Credentials linked together by a workflow, data may be queried by a combination of TraceablePresentation.workflow.definition and TraceablePresentation.workflow.instance, assuming that the implementation's underlying data store persists presentation metadata upon receipt. Rules for ensuring the retrieval of the most "correct" credentials associated for that workflow instance are covered below in the section on Credentials. 

Some discussion and explicit clarification of use of issuer SHOULD be added to the spec text to clarify best practices for retrieval and ownership of data

**Comment by nissimsan** [comment]
Add paragraph on what the server and client is expected to retrieve data.

**Comment by nissimsan** [comment]
@mprorock , will you please action this.

**Comment by OR13** [comment]
<img width="941" alt="Screen Shot 2023-07-11 at 1 08 37 PM" src="https://github.com/w3c-ccg/traceability-interop/assets/8295856/751f60af-69e1-44f9-9a83-178dcd320704">

^ this does not look great... any improvement to this is welcome.

**Comment by OR13** [comment]
Still needs some respec text, and to remove the issue marker.

**Comment by nissimsan** [comment]
Looking for volunteers on this.

**Comment by nissimsan** [comment]
@brownoxford , I did some work on this part of the respec. Pls re-review which parts of this is still relevant

**Comment by brownoxford** [comment]
Note, this is now section 9.1.1 in the spec. Also, the paragraph in question has been entirely removed and it appears that details of `Workflow` are now specified in the [trace vocab spec](https://w3c-ccg.github.io/traceability-vocab/#workflows).

@OR13, this issue was originally raised by you, do you still feel that we need to make modifications to the interop spec?

**Comment by mkhraisha** [comment]
as discussed on April 11th call, we no longer think this is necessary.
