### ISSUE TITLE
Specify precise usage of id for members of credentials

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#497]
Section 8.1.2 of the spec includes the following paragraph:

> In the case of credentials used in systems implementing this specification, a credential ID MUST be a UUID v4 per [[rfc4122](http://localhost:3000/spec/#bib-rfc4122)]. The issuing system MUST return the credential in question with an HTTP request to their API of GET /credentials/{credential-id}

This specification needs to specify precise usage of id for members of credentials as well, in the furtherance or reuse of data already defined elsewhere with a defined id, e.g., an address, or other commonly repeated object

**Comment by nissimsan** [comment]
This is difficult to tackle. No one on the call seem able to make tangible suggestions how to progress this.

**Comment by OR13** [comment]
https://w3c-ccg.github.io/traceability-vocab/#extensions-to-standard

addresses the data model part.

**Comment by nissimsan** [comment]
Closing
