### ISSUE TITLE
Monitor successors to revocation list 2020 for inclusion in the spec

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#498]
Section 12.2 of the spec contains the following paragraph:

> Any system conforming with this specification for interoperability MUST support[ Revocation List 2020](https://w3c-ccg.github.io/vc-status-rl-2020/) to handle revocation of Verifiable Credentials.

As later approaches to revocation stabilize, a successor approach is expected to replace Revocation List 2020, assuming future standardization of a replacement approach at a future date.

**Comment by nissimsan** [comment]
On hold until we feel comfortable adding StatusList2021.
