### ISSUE TITLE
How should duplicate IDs for traceable presentations be handled?

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#502]
A recent PR added the following text to the spec:

> TraceablePresentation.id MUST be unique to each presentation. A presentation received with a duplicate ID MUST be rejected with a 409 Conflict status code per [[rfc9110](http://localhost:3000/spec/#bib-rfc9110)]. A presenter encountering this error, SHOULD generate a new presentation, with a new UUID v4 for the ID and then retry the presentation.

@OR13 called out that this addition requires an issue and further discussion. We will need to make other modifications, e.g., to documentation, OpenAPI specs, etc. once this is fully hashed out.

This issue exists as a placeholder to comment on this change and potential further required actions.

**Comment by brownoxford** [comment]
See #485 for ongoing related discussion.

**Comment by nissimsan** [comment]
A duplicate indicates that the holder party has not implemented the spec correctly. 
A duplicate `presentation.id` should be returned as an error.

**Comment by nissimsan** [comment]
PR to add wording on to the respec: 

https://w3c-ccg.github.io/traceability-vocab/#extensions-to-standard

Add to this section that it must be a unique `urn:uuid`.

**Comment by brownoxford** [comment]
We also need to remove this language regarding specification for `presentation.id` from the interop spec, as this exists and is defined in the vocab spec.

**Comment by OR13** [comment]
Seems like we should refer to vocab from interop, not redefine vocab in interop.
