### ISSUE TITLE
Update OAS section of spec with codegen links

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#503]
Regarding the "OAS Implementation" section of the respec document, @OR13 commented:

> We might want to provide some links related to code gen here... such as:
> https://www.npmjs.com/package/openapi-typescript-codegen

This section should be updated to add relevant links and possibly usage examples for generating clients using the OAS yaml files.

**Comment by nissimsan** [comment]
Add additional documentation on the respec.

**Comment by OR13** [comment]
Add a sentence about how to code gen client sdk from oas.

**Comment by nissimsan** [comment]
@brownoxford , any progress on this?

**Comment by nissimsan** [comment]
Ping @brownoxford
