### ISSUE TITLE
need to finalize signing / verify methods

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-interop#506]
we need to clarify and finalize a list of signature suites and signing mechanisms, especially in light of performance implications for the volumes of data that we are dealing with - personal preference is to standardize around [some kind of jws](https://transmute-industries.github.io/vc-jws/)

**Comment by nissimsan** [comment]
ES384 should be mandated as a must.

**Comment by OR13** [comment]
suggest ES384 as a MUST.

**Comment by nissimsan** [comment]
Related, similar work: 
https://github.com/w3c/vc-jose-cose-test-suite/blob/main/testcases/secured-vc-with-schema/spec.yaml

No need to work on this in parallel. Better to wait for it to finish, then copy.

**Comment by OR13** [comment]
Suggest adding text to respec document citing nist guidlines, and mark as ready for PR.

**Comment by rhofvendahl** [comment]
@OR13 is still interested, but blocked pending v2 discussion

**Comment by mkhraisha** [comment]
@OR13 @mprorock do you feel this should be part of v1.0?
personally i believe we should do it as part of v1.0

**Comment by OR13** [comment]
Yes, I think we should have mandatory to support crypto and format requirements, or the profile is not useful.

**Comment by mkhraisha** [comment]
This has been merged in and we agreed to ES384 as a must.
