### ISSUE TITLE
Bad Conformance Test `credentials_issue:credential.@context:invalid`

### ISSUE THREAD

**Issue by ipbyrne** [w3c-ccg/traceability-interop#512]
We have a conformance test that requires `https://w3id.org/traceability/v1` in its context. The `credentials_issue:credential.@context:invalid` test should be removed.

**Comment by mkhraisha** [comment]
Why is this an invalid conformance test? 

I'm looking through the spec right now and I can't find the normative requirement to have `https://w3id.org/traceability/v1`  in the context but I believe it should be required to pass this test suite.

**Comment by brownoxford** [comment]
This should not be an issue to remove the test, rather it should be an issue to modify the OpenAPI spec [Credential.yml](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/Credential.yml) to remove the requirement for the URL to be in the context (modifying the test would be part of the process for resolving the issue).

```
properties:
  '@context':
    description: |
      The JSON-LD Context defining all terms in the Credential. This array
      MUST contain "https://w3id.org/traceability/v1".
    type: array
    items:
      type: string
```

That being said, I also don't fully understand the reason for removing this requirement.

**Comment by brownoxford** [comment]
@ipbyrne The tests are currently implemented to test the requirements in the OpenAPI spec. Before we delete or modify tests, we need to have some discussion about whether or not the spec should be modified - if we agree it should be modified, then it should be modified and the relevant tests updated to reflect the new state of the spec.

**Comment by mkhraisha** [comment]
I'm not sure whats going on with my earlier comment on this thread, but I'll repost the gist of it again: 

Why are we removing traceability vocab as a requirement from the traceability interop context?

**Comment by brownoxford** [comment]
@ipbyrne The traceability interoperability specification extends the core Verifiable Credential API definitions described in the VC-API specification, so there will be normative requirements that are not present in the VC API specification (but which are still conformant to the VC API specification).

> you are making them choose between conforming to the VC API spec, or the custom trace version of it.

I disagree, a VC with `https://w3id.org/traceability/v1` in the `@context` is still conformant to the VC API specification.

**Comment by brownoxford** [comment]
> If someone builds their API to conform to this requirement (enforcing the trace context being required), their API can only issue trace interop credentials, which means they can't issue any other ones.

This does seem like something we should evaluate. An implementation should be able to conform to the trace-interop spec without being prevented from issuing other types of credentials. @mkhraisha does this answer your concerns as well?

**Comment by mkhraisha** [comment]
As a general guiding principle, we want the ability to interop with the VC-API spec as much as possible. 
I agree we need to tailor our generic credential object more narrowly, I think it is important to have some places where the `@context` requires `https://w3id.org/traceability/v1`. 

`/credentials/issue` should not be one of those places, if I wish to issue a credential that uses a different vocabulary and does not touch trace, I should not be prevented from doing so. 

I believe a response to an issued credential that utilizes the trace vocab must include the `https://w3id.org/traceability/v1` context.

**Comment by OR13** [comment]
speaking from a "JSON-LD" perspective, it is possible for us to replace context and still validate a "data integrity proof"... so a GS1 VC like:

```
"@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1",
    "https://w3id.org/vc/status-list/2021/v1"
  ],
  ```
  
  Can actually become:
  
  ```
   "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  ```
  
  if we define all the terms correctly in 
  
   "https://w3id.org/traceability/v1"

**Comment by mkhraisha** [comment]
> So @brownoxford and @mkhraisha How does this sound for a proposed solution:
> 
> 
> 
> 1. Remove the trace URL requirement from `Credentials.yml`.
> 
> 2. Remove the associated test with this requirement.
> 
> 3. Update The `Credential Create - Positive Tests` so they confirm issued VCs have `https://w3id.org/traceability/v1` in the credential context in the request responses.
> 
> 
> 
> 

Sounds good to me

**Comment by brownoxford** [comment]
I'm not 100% sure why this was required in the first place - I can see that it was me who added it in c4b792b98, but I have no memory of the specific reason. Would it not be a better test to proceed as @ipbyrne suggested with the modification that instead of checking for `https://w3id.org/traceability/v1` in the response from `/credentials/issue` we simple ensure that all of the values provided in `@context` in the request are still present in the response?

**Comment by OR13** [comment]
> This test requires an id to be present in the VC when it's sent to `/credentials/issue`

It is a `credential` that is present in the post body, not a `VC`... although the WG has not yet fully agreed on this point.

- https://github.com/w3c/vc-data-model/pull/1014

- https://github.com/w3c/vc-data-model/issues/1031

I suggest opening a PR to make `credential.id` OPTIONAL and `verifiable credential.id` required.

**Comment by mkhraisha** [comment]
It should be possible for a context in the request object to be omitted from the response object and still be valid json-ld.

This can be done by the issuer mapping the definitions to similar ones present in another vocabulary providing something that the requester wasn't expecting, I think the test should be do the context objects match, not is trace context present

**Comment by nissimsan** [comment]
New issue: make an interop test based on a GS1 credential (without trace context).

**Comment by nissimsan** [comment]
Closing this.
