### ISSUE TITLE
Improvements to the abstract

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-interop#528]
The current abstract has a number of issues associated with it and it should be rewritten with the following changes:

1. Abstract should be 3-5 paragraphs
2. More business framing
3. Direct links to related references including: 
- DID Spec
- VC Spec
- Trace Vocab spec
4. references VC API should be moved to its own section "Relationship to VC-API"

**Comment by nissimsan** [comment]
Sounds good.

**Comment by nissimsan** [comment]
There are still pending issues on the respec

**Comment by rhofvendahl** [comment]
@mkhraisha Pinging
