### ISSUE TITLE
New Section: Relationship to VC-API

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-interop#529]
The spec should have a section that outlines the relation ship of the Trace Interop to the VC-API

**Comment by nissimsan** [comment]
Yes. Please update the wording on this.

**Comment by nissimsan** [comment]
Ping @mkhraisha , updates on this?

**Comment by rhofvendahl** [comment]
@mkhraisha Pinging

**Comment by mkhraisha** [comment]
per patrick's comment we should  point out the options field discrepancy between vc api and trace api.

**Comment by PatStLouis** [comment]
Can we close #589 and refer to it in this issue? We have confirmed there was no misalignment now we just need a mention of this in a PR. @mkhraisha  You can assign this to me.

**Comment by mkhraisha** [comment]
This should basically say go to VC API to figure out communication within trust boundary.

The should say the only thing we care about is interoperable communication across trust boundaries in a supply chain setting.

**Comment by mkhraisha** [comment]
@PatStLouis to work on it soon.

**Comment by mkhraisha** [comment]
@PatStLouis any updates?

**Comment by nissimsan** [comment]
Issue pending PR resolve.
