### ISSUE TITLE
Move specific examples to the appendix

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-interop#531]
We should move the CBP specific workflow examples to the appendix and instead create a generic workflow example to make the spec more inclusive

**Comment by nissimsan** [comment]
Related to https://github.com/w3c-ccg/traceability-vocab/pull/853

@mkhraisha , pls comment on that PR

**Comment by nissimsan** [comment]
I also believe this is in the wrong repo. Workflows are on vocab.

**Comment by mkhraisha** [comment]
Approved that PR
I believe action now is to remove references to CBP workflow from this profile

**Comment by nissimsan** [comment]
Ping @mkhraisha

**Comment by nissimsan** [comment]
We merged this today
