### ISSUE TITLE
Fixes to the Intro

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-interop#532]
The intro should not include the depth of technical information that it currently contains - for example, discussing presentation auth flow probably doesn’t belong here (regardless of whether we keep or remove that flow).

1.1 Section title should probably change.

The intro should expand on all the points outlined in the new abstract #528 

A grammar exists error in the intro: 
This is used by the presenter for proving the Verifiable Presentation, which finally passed to the receiver.

**Comment by OR13** [comment]
@mkhraisha please open a PR when you get a chance

**Comment by nissimsan** [comment]
@mkhraisha , progress on this?

**Comment by nissimsan** [comment]
Ping @mkhraisha

**Comment by mkhraisha** [comment]
I have not worked on it yet, will tackle.

**Comment by nissimsan** [comment]
Dupe'ish: https://github.com/w3c-ccg/traceability-interop/issues/647

**Comment by nissimsan** [comment]
https://w3c-ccg.github.io/traceability-interop/draft/#introduction should describe more narrowly the purpose of the spec:

Supply chain data exchange
Cross security-boundary

**Comment by mkhraisha** [comment]
This is tackled by #653
