### ISSUE TITLE
Changes to Section 6

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-interop#533]
Updates to section four:
Suggestions: 

Move all normative items from section 4 to section 8 with a potential title change for section 8.

- [ ] Section 4 title should be changed to Use Cases.
- [ ] It is currently marked as non-normative but has subsections that _are_ normative this should be fixed.
- [ ] 4.1 should remove the sentence saying we require .well-known did configuration - this is not true.
- [ ] 4.1.1 Belongs in normative requirements

**Comment by nissimsan** [comment]
@mkhraisha ping

**Comment by OR13** [comment]
@mkhraisha please open a PR when you get a chance

**Comment by nissimsan** [comment]
@mkhraisha , pls move this forward.

**Comment by nissimsan** [comment]
Ping @mkhraisha

**Comment by rhofvendahl** [comment]
@mkhraisha Ping

**Comment by nissimsan** [comment]
https://w3c-ccg.github.io/traceability-interop/draft/#use-cases-and-requirements

**Comment by mkhraisha** [comment]
All references to section 4 are now to section 6 use cases and requirements.

**Comment by mkhraisha** [comment]
@nissimsan to create a new issue that will update the requirements on the respec document changes
