### ISSUE TITLE
statements about deployment architecture

### ISSUE THREAD

**Issue by Sakurann** [w3c-ccg/traceability-interop#542]
[This interop document](https://w3c-ccg.github.io/traceability-interop/draft/#workflows-for-us-customs-and-border-protection-us-cbp) seems to define deployment architecture even in the places that do not affect interoperability.
For example, the following statements:
> Conformant platforms MAY be either single-tenant or multi-tenant.
> The DID Document MAY be hosted on a 3rd party web server.

These kind of statements regarding deployment architecture of the implementations should be out of scope from the profiles and be removed from this profile.

**Comment by nissimsan** [comment]
The spec defines an HTTP API. It's relevant to comment on the endpoint structure. 

Disagreement on the issue on the call.

**Comment by OR13** [comment]
Seems like we need to comment on this given the resource server and authorization schemes we require.

**Comment by nissimsan** [comment]
I'll remove this section.
