### ISSUE TITLE
who initiates the interaction

### ISSUE THREAD

**Issue by Sakurann** [w3c-ccg/traceability-interop#544]
[Introduction](https://w3c-ccg.github.io/traceability-interop/draft) says `the presenting party initiates an interaction, notifying the receiver.` I have read the document but have not found any normative requirements around this. Have I missed something or is it not a normative requirement?

**Comment by nissimsan** [comment]
This is the /available endpoint. 

Will need rewriting though.

**Comment by nissimsan** [comment]
@nissimsan, poke

**Comment by nissimsan** [comment]
Raise a PR and let that be driving the decision to purge DIDAuth.
