### ISSUE TITLE
Reports are not properly being stored

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#546]
Right now, the date on both conformance and interop reports is 4/28, and all archived reports from 4/28 until now are missing.

**Comment by brownoxford** [comment]
GitHub pages artifact has exceeded the maximum of 10GB, investigating.

**Comment by brownoxford** [comment]
Nightly reports are quite large, with the bulk of the space being taken up by the `index.html` file for each archived report. Current archived report size is about 16M for interop, and 26M for conformance.

Long term, we need to optimize the HTML that is generated, e.g., to use stylesheets instead of inline styles, etc.
Short term, we need to roll off some of the older archived reports.

Current archive goes back to 2022-08-23, I propose we prune this to a rolling three month archive.

**Comment by brownoxford** [comment]
I looked into the short-term possibilities outlined above, and the problem is the overall size of the files contained in the `gh-pages` branch. In order to remediate this we will need to prune the archive.

**Comment by mkhraisha** [comment]
Maybe last 3 months reports are the only ones we should keep as a starting point?

**Comment by brownoxford** [comment]
I've pruned the backlog of archived tests to three months, and the links in the main README.md are now working. I'll create a few new tickets to address some long-term things that we should discuss.
