### ISSUE TITLE
Documentation and Spec needs updating for scope changes

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#551]
Existing documentation (tutorials, respec, etc.) need to be updated to reflect the changes made to scope requirements in PR #545

**Comment by brownoxford** [comment]
to be clear, tests related to scopes will be removed

**Comment by OR13** [comment]
I suggest we remove all scope specific tests, and update documentation to "informative guidance" not requirements.

**Comment by nissimsan** [comment]
@brownoxford , is anything blocking you for progressing this?
