### ISSUE TITLE
Need to define how and what workflows are

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-interop#56]
Need a definition and core structure and description for the notion of workflows in the context of tracing an item or shipment

**Comment by OR13** [comment]
Related to https://github.com/w3c-ccg/traceability-interop/issues/85

We should close this once we can link to the vocab defintion for workflows.

**Comment by OR13** [comment]
close this as a dupe.

**Comment by mprorock** [comment]
dupe #85
