### ISSUE TITLE
Remove references to JsonWebSignature2020

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-interop#562]
We should remove all references to JsonWebSignature2020 as that work item is being withdrawn.

https://github.com/w3c/vc-jws-2020

**Comment by OR13** [comment]
+1 , we need to switch to vc+ld+jwt and vp+ld+jwt

**Comment by OR13** [comment]
https://github.com/search?q=repo%3Aw3c-ccg%2Ftraceability-interop%20JSONWebsignature2020&type=code

**Comment by OR13** [comment]
PR exists https://github.com/w3c-ccg/traceability-interop/pull/581

**Comment by OR13** [comment]
Only 1 more reference remaining https://github.com/search?q=repo%3Aw3c-ccg%2Ftraceability-interop%20JSONWebsignature2020&type=code

**Comment by nissimsan** [comment]
Agility tutorial still needs updating. Otherwise this is done.

**Comment by rhofvendahl** [comment]
@mkhraisha Waiting on agility tutorial update
