### ISSUE TITLE
Use a Custom Trace Interop User Agent

### ISSUE THREAD

**Issue by ipbyrne** [w3c-ccg/traceability-interop#567]
It would be nice if our conformance postman tests used a specific user agent so you can filter our requests from that agent when reviewing server request logs.

It currently uses `PostmanRuntime/7.29.0`, which does help filter out postman requests but would be nice if it was more granular.

**Comment by nissimsan** [comment]
@ipbyrne , we did this - can you confirm so we can close the issue?

**Comment by ipbyrne** [comment]
Confirmed this is done!
