### ISSUE TITLE
Update relevant unit tests to include "Accept" header in requests

### ISSUE THREAD

**Issue by rhofvendahl** [w3c-ccg/traceability-interop#574]
Currently the Accept header is used in Issue and Verify requests to specify the format of the verifiable credential. Legitimate values are vc (for json VCs with linked data proofs), vc-jwt, and (pending discussion) vc-cwt.

**Comment by rhofvendahl** [comment]
Use of Content-Type is now uncertain - see discussion on https://github.com/w3c-ccg/traceability-interop/pull/573

**Comment by nissimsan** [comment]
Ping @rhofvendahl

**Comment by rhofvendahl** [comment]
@OR13 when we discussed this in August I believe you recommended making an issue (https://github.com/w3c/vc-jose-cose-test-suite/issues/8) in https://github.com/w3c/vc-jose-cose-test-suite, so that these changes could be referenced by multiple projects. It's looking like there hasn't been any activity in that project in the past month, though.

Do you know if that project is still moving forward? If it isn't actively being worked on, I'd be happy to move ahead with implementing this in the trace-interop repo.

**Comment by OR13** [comment]
Yes, prefer work to be done in a place where the working group can benefit

**Comment by rhofvendahl** [comment]
So you do expect vc-jose-cose-test-suite project to move forward? If that's the case I suppose I should just take on the issue there, as there doesn't seem to be many active developers at this time.

**Comment by rhofvendahl** [comment]
Still WIP

**Comment by rhofvendahl** [comment]
I've broken this into two PRs: https://github.com/w3c-ccg/traceability-interop/pull/605 for updating Accept headers, and https://github.com/w3c-ccg/traceability-interop/pull/606 for adding a test for the requirement of Accept.
