### ISSUE TITLE
Add negative unit testing for incorrect/missing Content-Type values in requests

### ISSUE THREAD

**Issue by rhofvendahl** [w3c-ccg/traceability-interop#575]
Currently the `Content-Type` header is used in Issue and Verify requests to specify the format of the verifiable credential. Legitimate values are `vc` (for json VCs with linked data proofs), `vc-jwt`, and (pending discussion) `vc-cwt`.

**Comment by rhofvendahl** [comment]
Use of Content-Type is now uncertain - see discussion on https://github.com/w3c-ccg/traceability-interop/pull/573

**Comment by OR13** [comment]
Lets cover:

- `application/vc+ld+json+jwt`
- `application/vp+ld+json+jwt`

`Accept` and `Content-Type`

**Comment by nissimsan** [comment]
Start by describing in respec the NDR which we are aiming for.

**Comment by OR13** [comment]
This file will need to be updated https://github.com/w3c-ccg/traceability-interop/blob/main/docs/spec/index.html

**Comment by nissimsan** [comment]
Closing - covered in other issues.
