### ISSUE TITLE
Update respec document with normative language describing use of Content-Type

### ISSUE THREAD

**Issue by rhofvendahl** [w3c-ccg/traceability-interop#576]
Currently the `Content-Type` header is used in Issue and Verify requests to specify the format of the verifiable credential. Legitimate values are `vc` (for json VCs with linked data proofs), `vc-jwt`, and (pending discussion) `vc-cwt`.

**Comment by rhofvendahl** [comment]
Use of Content-Type is now uncertain - see discussion on https://github.com/w3c-ccg/traceability-interop/pull/573

**Comment by nissimsan** [comment]
Thank you @rhofvendahl  for self assigning

**Comment by rhofvendahl** [comment]
@rhofvendahl WIP

**Comment by rhofvendahl** [comment]
On inspection, at this time the respec document doesn't have much to say about the specifics of issue and verify requests. It may be worthwhile expanding the document to cover issuance and verification, but the intent of this PR was to get all of the docs on the same page about Accept, so that seems somewhat out of scope.
