### ISSUE TITLE
Interop summary page improvements

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-interop#582]
1. Add a column to the Provider summary for overall 
 
![image](https://github.com/w3c-ccg/traceability-interop/assets/19310771/32aebaaa-df1e-4d0f-8bf5-b5673cf50aab)

2. Use product offering instead of company names.

**Comment by TallTed** [comment]
It's fine to use company names *with* product names, so a company might be seen on multiple columns, but we must remember that one company may have test results for multiple products and/or multiple versions of a single product.

**Comment by OR13** [comment]
Suggest change to "Transmute - TypeScript / REST/ JSON" for us at least.

**Comment by nissimsan** [comment]
@mkhraisha, would you be willing to assign yourself on this?

**Comment by rhofvendahl** [comment]
@mkhraisha Ping

**Comment by TallTed** [comment]
It would help folks trying to find the summary page, if a link to that page were added this issue. (I recommend editing the initial comment.)

**Comment by mkhraisha** [comment]
https://w3c-ccg.github.io/traceability-interop/reports/interoperability/ is where the summary can be found, this is not a high priority issue.

**Comment by mkhraisha** [comment]
As we are moving to the new fixtures test framework, we will no longer need this issue, as the entire table is being removed. #659 should also modify reporting to the new fixtures test.
