### ISSUE TITLE
Review the CHAPI Playground and Newly Added Protocols

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#588]
CHAPI Playground was recently updated, see:

- https://lists.w3.org/Archives/Public/public-credentials/2023Aug/0054.html

We should discuss if CHAPI support is planned, and if OIDC4VCI support is planned.

**Comment by OR13** [comment]
@mprorock would you object to more content regarding CHAPI ?

Should we do CHAPI or not?

**Comment by rhofvendahl** [comment]
Closing as no one on call has interest, can be re-opened if that changes
