### ISSUE TITLE
Presentation Notify - Requester Identification in Request Body

### ISSUE THREAD

**Issue by coran-coley** [w3c-ccg/traceability-interop#602]
For the "Notify" endpoint (presentations/available) the documentation for both [OpenAPI](https://w3c-ccg.github.io/traceability-interop/openapi/#post-/presentations/available) and the [spec](https://w3c-ccg.github.io/vp-request-spec/#query-by-frame) doesn't  appear to have an identifier for the caller integrated into the request. 

This makes it difficult to ensure that the challenge used in a subsequent "Submit" call is being presented by the intended entity while keeping strictly to the spec for data exchange between partners (ie without demanding the information be added to a header or similar). Would it make sense for the DID of the endpoint caller be added to the request body of "Notify" so that the endpoint owner knows the identity of the entity they are returning a specific challenge to? Thank you.

Ex (request body from OpenAPI used):
```
{
  "query": [
    {
      "type": "QueryByExample",
      "requesterDid": "did:web:example.com:1234" //Proposed addition
      "credentialQuery": [
        {
          "type": [
            "VerifiableCredential"
          ],
          "reason": "We want to present credentials."
        }
      ]
    }
  ]
}
```

**Comment by mkhraisha** [comment]
refer to #604 to remove this documentation discrepancy
