### ISSUE TITLE
Require accept header

### ISSUE THREAD

**Issue by rhofvendahl** [w3c-ccg/traceability-interop#609]
Do we want VC API implementations to require `Accept` headers in "create credential" requests, returning `400` status if the header isn't present? If yes, we'll want to update the spec with normative language and approve https://github.com/w3c-ccg/traceability-interop/pull/606, which would add negative testing for this.

**Comment by brownoxford** [comment]
Another alternative is to NOT require an `Accept` header, and return `application/vc+ld+json` by default.

**Comment by rhofvendahl** [comment]
It was decided on today's trace call that it does not make sense to return an error if a request Accept header is missing. An error should be returned if a media-type requested by the client is not available, but if the header is absent then the server should just return the default value.
