### ISSUE TITLE
@context values can be objects according to the spec, conformance test-suite will raise this as a failed step

### ISSUE THREAD

**Issue by PatStLouis** [w3c-ccg/traceability-interop#624]
Two of the conformance negative tests will assert that context values can't contain `@vocab` objects. However in the [vc-data-model 1.1 spec](https://www.w3.org/TR/vc-data-model/#contexts) it states that:

> Subsequent items in the array MUST express context information and be composed of any combination of [URIs](https://www.w3.org/TR/vc-data-model/#dfn-uri) or objects.

Any reason for this misalignment from the vc-data-model 1.1 specification?

**Comment by mkhraisha** [comment]
ping Patrick to cycle this issue, we have a PR open just pending feedback changes

**Comment by mkhraisha** [comment]
This is no longer relevant, see #631
