### ISSUE TITLE
Reschedule meeting cadence

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-interop#636]
I have a meeting collision, can we reschedule, pls? 

Proposing Thursdays 3:00pm EST (21:00 CET).

**Comment by PatStLouis** [comment]
Would need to update the [w3c-ccg announcements](https://w3c-ccg.github.io/announcements/) page and other public meeting information. I'm ok with the proposed time.

**Comment by TallTed** [comment]
For updating meeting times -- note that this meeting is on https://calendar.google.com/calendar/u/0/embed?src=6a4bq17no84ssnadccm0j2133g@group.calendar.google.com&ctz=America/New_York 
(owned by w3c.ccg@gmail.com)

it's not on https://www.w3.org/groups/cg/credentials/calendar/

Probably, the Gcal should be emptied, and all events moved into the W3Ccal.

**Comment by mkhraisha** [comment]
@w3c-ccg/chairs are we able to modify those calendars?

**Comment by TallTed** [comment]
I've emailed [w3c.ccg@gmail.com](mailto:w3c.ccg@gmail.com) in hopes someone still sees messages sent there, and can address [*that* calendar](https://calendar.google.com/calendar/u/0/embed?src=6a4bq17no84ssnadccm0j2133g@group.calendar.google.com&ctz=America/New_York).

I have hopes that CCG chairs (attn @wip-abramson, @kwlinson, @man4prez) can figure out getting these onto the [W3C CCG Calendar](https://www.w3.org/groups/cg/credentials/calendar/) soon!

Worst case, once all future meetings are moved to the W3C Calendar, subscribers can drop the CCG's Google Calendar (so its erroneous future entries cause no further confusion).

**Comment by mkhraisha** [comment]
@wip-abramson @kwlinson @man4prez can you add us to the W3C CCG Calendar!

Our timeslots are Thursday 3pm EST.
