### ISSUE TITLE
Add additional code generation languages

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-interop#645]
https://w3c-ccg.github.io/traceability-interop/draft/#code-generation

Ideally we would have subsections with different code gen. languages, not only type script.

**Comment by mkhraisha** [comment]
Personally not sure we should keep all of Section 9.1 in the spec at all.

**Comment by mkhraisha** [comment]
Resolved to just remove section 9.1 from the spec.

**Comment by PatStLouis** [comment]
Can you assign me please

**Comment by nissimsan** [comment]
@PatStLouis confirmed assigned

**Comment by mkhraisha** [comment]
@PatStLouis following up on this
