### ISSUE TITLE
Update section "Interop Testing"

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-interop#657]
https://w3c-ccg.github.io/traceability-interop/draft/#interoperability-testing

To be updated with the actual approach to interop testing: 

- Discovery through did:web
- Pre-issued JWT (to avoid having to call /issue)
- OAuth Client Credentials authentication 
- Successful call to /presentations

**Comment by TallTed** [comment]
Section numbers change. Please always reference them by title, which may *include*, but should not be reduced to, the number.

**Comment by mkhraisha** [comment]
There is a proposal here: https://github.com/w3c-ccg/traceability-interop/issues/659#issuecomment-2181380800

If we agree on that we can go ahead and udpate the spec language on how to do interop tests to reflect our new thinking

**Comment by brentzundel** [comment]
assign me
