### ISSUE TITLE
Move to redoc from swagger

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#66]
I propose we consolidate the api definitions, follow the OAS 3.0 boilerplate guidelines (split parameters, schemas, responses, resources).

and have the respec just link to the OAS 3 Redoc like we do in trace-vocab.

Happy to do the work if folks are ready for it to be done... here is a preview of what it should look like (minus branding):

https://api.did.actor/docs 

(happy to apply W3C CCG branding if we have an asset for that).

**Comment by mprorock** [comment]
big fan of redoc and this approach - also happy to help

**Comment by OR13** [comment]
Implemented in https://github.com/w3c-ccg/traceability-interop/pull/69

**Comment by OR13** [comment]
we did it
