### ISSUE TITLE
Postman testing artifacts should be available for review

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#75]
The HTML output from postman tests should be available for review.

**Comment by OR13** [comment]
I think we can possibly just push the built assets to a directory in github pages as a first step.

**Comment by brownoxford** [comment]
@OR13 Agreed, that's the direction I'm leaning in. I was planning on seeing whether we can aggregate results into something more easily used, possibly with something like https://github.com/ervirendersingh/newman-reporter-allure. I want to solve for the issue where each postman run generates a wholly separate output file, which would get tedious to digest.

**Comment by brownoxford** [comment]
I'm currently working on a PR for this issue that will append newman output as build artifacts and also publish individual output to a subfolder of the gh-pages deployment.

**Comment by OR13** [comment]
artifacts need to be sanitized before a report can be generated.

**Comment by OR13** [comment]
https://w3id.org/traceability/interoperability/reports
