### ISSUE TITLE
Postman tests should not run on PR from outside repo

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#76]
Current test in `ci.yml` uses the following conditional:

```yaml
if: github.repository == github.event.repository.full_name
```

This does not seem to be working though.

**Comment by OR13** [comment]
yea, this is tough for cross fork PRs.

**Comment by OR13** [comment]
for now, lets grant contributors write access and have them run tests without cross forking.

**Comment by OR13** [comment]
closing this issue, ask to be a contributor and we will give you  write access, until further notice.
