### ISSUE TITLE
Terminology defined incorrectly

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#85]
IMO we should not be defining ANY terminology that is not relevant to the HTTP interop profile  in this repo...

We should especially not be defining VP or VC data model items in this repo.

Also the current terminology is incorrectly defined.

![Screen Shot 2022-02-08 at 10 43 18 AM](https://user-images.githubusercontent.com/8295856/153034029-07d93e62-0f2b-420c-849f-6de7ba00639a.png)

**Comment by mprorock** [comment]
To clarify on this issue:
All core terminology belongs here in the Traceability Vocab [spec](https://github.com/w3c-ccg/traceability-vocab/) and updated in the [repo for that spec](https://w3c-ccg.github.io/traceability-vocab/)

This repo should then in the terminology section reference the Vocab, and then define any new terms that are specific to the interop profile iteself

**Comment by OR13** [comment]
This issue can be closed when the red squiggles are gone.

**Comment by BenjaminMoe** [comment]
On it

**Comment by OR13** [comment]
Still broken
![Screen Shot 2022-04-19 at 1 07 42 PM](https://user-images.githubusercontent.com/8295856/164067990-01736721-af54-4ccf-967e-c382a7fb8040.png)

**Comment by brownoxford** [comment]
This is no longer broken in the traceability-interop repo (https://w3c-ccg.github.io/traceability-interop/#terminology), but is still outstanding in the traceability-vocab repo (https://w3c-ccg.github.io/traceability-vocab/#terminology).

I've reproduced @BenjaminMoe 's PR at https://github.com/w3c-ccg/traceability-vocab/pull/386, I believe this issue can now be closed.

**Comment by OR13** [comment]
This was fixed.
