### ISSUE TITLE
Define or forbid human readable `exchange-id`

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#87]
consider:

POST /exchanges/credential-refresh
POST /exchanges/definition-oil-import-from-ca
POST /exchanges/definition-steel-import-from-mx

vs

POST /exchanges/urn:uuid:123

is guessable names a security issue?

if we support a single human readable name, does that mean we support all the other ones?

where is the registry for human readable "workflow definition names" maintained.

**Comment by mprorock** [comment]
if you have a GET for /exchanges and are authorized i would assume you get a list of supported workflows, names, descriptions based on auth - I am working on a PR for this on VC-API

**Comment by OR13** [comment]
Is there a better issue or PR to track this against?

**Comment by mprorock** [comment]
related most strongly to [this](https://github.com/w3c-ccg/vc-api/issues/259)

**Comment by OR13** [comment]
Seems blocked by VC-API change set negotiations.

**Comment by nissimsan** [comment]
Unassigning myself, as we just decided to wait with this.

**Comment by brownoxford** [comment]
ping @mprorock

**Comment by mkhraisha** [comment]
VC API defines an exchanges API, our goal on the traceability interop API is to be a superset of the VC-API, and as such we should support `/exchanges`.

**Comment by OR13** [comment]
we don't need to change anything to make them IRIs... they are already supposed to be IRIs given we are using JSON-LD.

we might need to relax "MUST" statements in the profile that speak to UUIDs

**Comment by nissimsan** [comment]
@OR13, 

> we might need to relax "MUST" statements in the profile that speak to UUIDs.

Yes, if I remember the conversation correctly this was the essential part.

**Comment by BenjaminMoe** [comment]
Proposal for resolution:

- [ ] We allow for human readable paths for exchange end points
- [ ] We DO NOT allow for human readable paths for exchange end points

1. We agree on this definition
2. We have updated the spec to reflect this.

**Comment by nissimsan** [comment]
As far as I can tell nowhere in the spec do we actually have this "MUST" suggested in this issue. So I agree we can just go ahead and close this ticket.

**Comment by nissimsan** [comment]
@OR13, are you okay to close this?

**Comment by OR13** [comment]
I'm good to close this, not planning to implement at this time.
