### ISSUE TITLE
Authenticated VPs are Redundant when Client Credentials access tokens are present

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#95]
Should we need to sign VPs when they are presented over a channel that is authenticated?

Can we improve performance by relying on the channel authentication?

How might this impact the VC-API and exchange APIs?

**Comment by OR13** [comment]
No reason to do "DID Auth" if you already did "OAuth2.0" standard client auth.

**Comment by OR13** [comment]
Just to be clear, VPs are not required to be "signed"... so a VP with no proof is legal per the spec.

**Comment by OR13** [comment]
This would seem to help with "throughput" of messages.

**Comment by OR13** [comment]
I related security issue: https://github.com/w3c-ccg/traceability-interop/issues/124

**Comment by mkhraisha** [comment]
I generally agree with that statement, if over an authenticated channel we should not need to Auth VPs

**Comment by nissimsan** [comment]
Same here - I see no reason to double authenticate.

We seem to be good on this - there's no proof on the (oauth secured) /presentations: 
https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/Presentation.yml

**Comment by nissimsan** [comment]
To be closed when tested and #210 is done.

**Comment by nissimsan** [comment]
Let's wait until we have tests in place before closing.

**Comment by brownoxford** [comment]
The authentication requirements for these endpoints is also covered in the following issues.
#242 #243 #246
