### ISSUE TITLE
Mutual certification of interoperability test conformance

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#96]
I have been considering scenario where each vendor might certify other vendors that have demonstrated a capability to pass an interoperability test.

In an ideal world, this might even be wired to github actions so that certification was automatically revoked when the vendor stopped passing the tests.

I believe this can be accomplished via postman and github actions.

**Comment by mprorock** [comment]
+1

**Comment by OR13** [comment]
I can take a stab at figuring out how we might do this.

**Comment by mprorock** [comment]
that would be great - we are a huge fan of this for both technical and marketing reasons

**Comment by OR13** [comment]
We might consider certifying the test reports generated here: https://w3id.org/traceability/interoperability/reports

**Comment by OR13** [comment]
plan is to certify the merged json used to build the "nice report"... blocked until that happens.

**Comment by mkhraisha** [comment]
Still Blocked by #200

**Comment by brownoxford** [comment]
This is no longer blocked.

**Comment by brownoxford** [comment]
First step is to define a schema for this.

**Comment by nissimsan** [comment]
Step one for this would be to define a schema.

**Comment by nissimsan** [comment]
We're essentially doing this already. 
Once we're passing tests we can reopen this.
