### ISSUE TITLE
Remove "checks"

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#97]
they got removed from the vc api

**Comment by OR13** [comment]
https://github.com/digitalbazaar/di-ed25519-test-suite/issues/3

**Comment by brownoxford** [comment]
This has been fixed in #90 for the new postman tests only (legacy tests have not been updated)

**Comment by OR13** [comment]
The new tests assert behavior regarding checks, those assertions and the associated options need to be removed.

**Comment by OR13** [comment]
I will do my best to fix this.

**Comment by brownoxford** [comment]
I got you. Working on this right now.
