### ISSUE TITLE
Visualizing Postman Reports

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-interop#99]
See https://learning.postman.com/docs/sending-requests/visualizer/

We need to setup SOME visualization of postman reports asap, and iterate on it later.

At a minimum there should be a way to see the results of a report by visiting a web page, and there should be an index of the reports that helps you get to the latest run.

I think its fine for us to drop older reports over time, since a report from 2 years ago, means nothing today.

**Comment by brownoxford** [comment]
I'm working on a PR that will publish all newman output to a `/newman` subdirectory of the gh pages.

**Comment by brownoxford** [comment]
Related to #75

**Comment by OR13** [comment]
this work is in progress.

**Comment by brownoxford** [comment]
My current plan is to continue migrating to the unit-style testing in the docs/tutorials folder, then work on sanitization and report aggregation.
